---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder
  namespace: dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: coder-secret
    creationPolicy: Owner
    template: 
      data:
        # Coder
        CODER_PG_CONNECTION_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local.:5432/coder"
        CODER_OIDC_CLIENT_ID: "{{ .CLIENT_ID }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .CLIENT_SECRET }}"
        CODER_EXTERNAL_AUTH_0_CLIENT_ID: "{{ .GITHUB_CLIENT_ID }}"
        CODER_EXTERNAL_AUTH_0_CLIENT_SECRET: "{{ .GITHUB_CLIENT_SECRET }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: coder
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: coder
    - extract:
        key: cloudnative-pg