---
apiVersion: v1
kind: Service
metadata:
  name: postgres17-lb
  annotations:
    lbipam.cilium.io/ips: 10.100.90.61
spec:
  type: LoadBalancer
  ports:
    - name: postgres-vector
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres17-vector
    cnpg.io/instanceRole: primary