---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 3Gi
  monitoring:
    enablePodMonitor: true

  # TODO: Add S3 storage
  # backup:
  #   volumeSnapshot:
  #      className: csi-rbd-snapclass
  #      snapshotOwnerReference: cluster

  # plugins:
  #   - enabled: true
  #     isWALArchiver: true
  #     name: barman-cloud.cloudnative-pg.io
  #     parameters:
  #       barmanObjectName: versity-thestral
  #       serverName: postgres-v2
  bootstrap:
    initdb:
      database: app
      owner: postgres


    # recovery:
    #   source:  source
  # externalClusters:
  #   - name: source
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: versity-thestral
  #         serverName: postgres
