---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-external
spec:
  provider:
    type: Kubernetes
    kubernetes:
      service:
        type: LoadBalancer
        loadBalancerIP: 10.100.90.85