apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:UbZ7y294oTOQk66KqKMaj+hqkvfSVL6gssmKbV9qdGU=,iv:jLeOPZNZqmIIPjMtmRRteCAN87ddFQl5ggExZ3AMjIo=,tag:dGYGWP2B1P2Fv8XWyJg2nw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTWQ3dklxNW56YlB4SURH
        aWY0MzgyaWtNTVBycnB4VUhaL1VTRUZJL3p3CmF3QTQxazRrY29PdDhGczNzVEQ0
        VFRHWG5yamIra1NINFlxckhZazNCSWMKLS0tIEhZN1pnRWlsUVZzNm5zZHVrbmhw
        MVhqaVpCWCtoSHlRcXhlSDlHQVRsdVEKX5wTFTtLNriJ8X9z50Xvn3PAFA6gLIC0
        y+4LRxaScYciz0Ux972CQns7uNdGk3+vdkF/7SHVFejArPQDGvKQKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:05Z"
  mac: ENC[AES256_GCM,data:EFY3T0RH4hyf6yPIlQ1VgznKQqmoAtSsb4PKrI2C2iuaqEHpO0w6DvP9B3+GaSh1TAda9IO8kRP/odJeGf8fS4ktiihoUe2qA8VNLZuCV8Oeebt0/NzWmK6yJNQSbn9aeHADEQXYvDEss6mCnNEcmJXKldQlXNgHFtnb82Gk88g=,iv:UQa88uBF8kjXh+O2YQHQ3hWVsJWlVEc5S0uTB4UVhnM=,tag:XPNhaKyWgLspT8Z1DN8TsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
