---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotify
spec:
  interval: 30m
  chart:
    spec:
      chart: gotify
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      TZ: Europe/Vienna
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "gotify.${SECRET_DOMAIN}"
            paths:
              - path: /
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
