---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: obsidian-secret
    creationPolicy: Owner
    template:
      data:
        couchdb-user: "{{ .COUCHDB_USER }}"
        couchdb-password: "{{ .COUCHDB_PASSWORD }}"
  dataFrom:
    - extract:
        key: obsidian
