---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-mcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: outline-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: OUTLINE_API_KEY
      remoteRef:
        key: mcps/outline-mcp
        property: OUTLINE_API_KEY
