---
logger:
  default: info

mqtt:
  enabled: false

auth:
  enabled: false

tls:
  enabled: false

database:
  path: /config/frigate.db

ffmpeg:
  global_args: [-hide_banner, -loglevel, info]
  hwaccel_args: preset-vaapi

detectors:
  cpu:
    type: cpu
    num_threads: 4

# detectors:
#   ov_0:
#     type: openvino
#     device: CPU
#   ov_1:
#     type: openvino
#     device: CPU

# snapshots:
#   enabled: true
#   timestamp: false
#   bounding_box: true
#   retain:
#     default: 20

record:
  enabled: true
  retain:
    days: 7
    mode: all

objects:
  track: [person, dog]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

go2rtc:
    streams:
        corridor: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.104:554/stream1
        corridor_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.104:554/stream2
        garden_door: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.108:554/stream1
        garden_door_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.108:554/stream2
        living_room: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.133:554/stream1
        living_room_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.133:554/stream2
        living_room_couch: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.138:554/stream1
        living_room_couch_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.138:554/stream2
        garden_chicken: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.103:554/stream1
        garden_chicken_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.103:554/stream2
        garden_carport: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.134:554/stream1
        garden_carport_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.134:554/stream2
        kids_nils: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.137:554/stream1
        kids_nils_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.137:554/stream2

cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles: [record]
    detect:
      enabled: false

  living_room_couch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_couch
          input_args: preset-rtsp-restream
          roles: [record]
    detect:
      enabled: false

  corridor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/corridor
          input_args: preset-rtsp-restream
          roles: [record]
    detect:
      enabled: false

  kids_nils:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kids_nils
          input_args: preset-rtsp-restream
          roles: [record]
    detect:
      enabled: false

  garden_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_door
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_door_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 5

  garden_chicken:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_chicken
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_chicken_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 5

  garden_carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_carport
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_carport_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 5