---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird
spec:
  chartRef:
    kind: OCIRepository
    name: netbird
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  interval: 30m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    cluster:
      name: nexus
    managementURL: https://netbird.ds47.dev
    netbirdAPI:
      keyFromSecret:
        name: netbird-mgmt-api-key
        key: NB_API_KEY
    operator:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 256Mi
