---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TZ: "Europe/Vienna"
  TIMEZONE: "Europe/Vienna"
  LB_IP_KUBE_API: "10.100.10.70"
  LB_IP_EMQX: "10.100.10.201"
  LB_IP_EVCC_API: "10.100.10.202"
  LB_IP_FRIGATE_GO2RTC: "10.100.10.203"
  LB_IP_UNIFI: "10.100.10.204"
  LB_IP_MUSIC_ASSISTANT: "10.100.10.205"
  LB_IP_PG18VEC: "10.100.10.206"
  LB_IP_INFLUXDB: "10.100.10.207"
  LB_IP_DRAGONFLY: "10.100.10.209"
  LB_IP_POSTGRES_DB: "10.100.10.210"
  LB_IP_KGATEWAY_INTERNAL: "10.100.10.218"
  KOPIUR_OFFSITE_S3_BUCKET: "dd-80-homelab-bucket"
  KOPIUR_OFFSITE_S3_PREFIX: "nexus-k8s-cluster"
  KOPIUR_GARAGE_S3_ENDPOINT: "http://garage.storage.svc.cluster.local:3900"
  KOPIUR_GARAGE_BUCKET: "k8s-cluster-backup"
