apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  INTERNAL_DOMAIN: ENC[AES256_GCM,data:QX+bS4pd7rw+0EarC9o=,iv:2YEpziVB6pwWv3aoLrEzNCHnf2Wg3ij+K303VblVJh4=,tag:BtxlzBCzIvXoLv0ndAksSw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:y6dBeMlvCPY=,iv:+EBOt4Q3oeBFkZpT30wSQ24iM/iEXrbdix8JNtE+uQ0=,tag:D+C1D/1LK4IWu9aDD1rV7g==,type:str]
  NFS_SERVER: ENC[AES256_GCM,data:H9MNITpdka9ppraX64SYqD2dOfQ=,iv:6c/6GSEuXiN2xXdRyBY0fZvBulBW96LNDTQVzm/aEDA=,tag:XkNeuM3Boj3ofEv32qT7QQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOENRNktDNktrRy90Y2JY
        aEVsNEh5M0h2c1BCdWgrQkpNOXRadUErQzJnCndJdU0wODdFN1Q2aXFZYWFBRC95
        VEdGUGxvM0YwM2puVGQ4ek0zT3VFVFUKLS0tIDU4MWdpSDErN3MvenRlLzlmOWRx
        UWJQVUtXbHlNRHFBdHN4SEQ3QnVRWW8KIvCswhLA4uX+bzBVGkBDNdT0/I76Jjej
        H4aSooLGlF3aYqNsjPut3Cd9vxlw+ANdmmiVLoEYkumTRURcxkDJDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1drlg4urwuhv9n8wgyhjwau7agpxq30n7wsdyhh6u5w9nk6e9p3jsdsqvtm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-01T08:44:11Z"
  mac: ENC[AES256_GCM,data:eByDYytdGHwh5BXA4/rj5DiilxuOz44ttKGm+6dkLGzcoVpTic2qyB2Xl0Esd0T219PV4picSI4OtzX43x2vzo38GhAXeVsIqo/rkQ5Sre3PMi63wB+hgyFXYK5B8yBxdeouIZXpwFkqZxkL0L4yiCrZWPkavt3e3GBerGK56Ww=,iv:S3WvP9MxPYZ16ab0ranEe+tlzbonfp3aeb59gRAZFf0=,tag:I1Q6lI4/GHk4MOqEZGEfxw==,type:str]
  version: 3.13.1
