---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./cluster-settings.yaml
  - ./cluster-secrets.sops.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: _
      spec:
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-settings
            - kind: Secret
              name: cluster-secrets
