---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: frigate-secret
    template:
      templateFrom:
        - configMap:
            name: frigate-configmap
            items:
              - key: config.yml
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: frigate
