apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: profilarr
  dependsOn:
    - name: ceph-csi-rbd
      namespace: storage
  values:
    controllers:
      profilarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: santiagosayshey/profilarr
              tag: v1.1.2@sha256:da7883be74c1b69ac1735ce4238b1a77e12117e94c64355704bf27bac0aa34de
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 256Mi

    service:
      app:
        ports:
          http:
            port: 6868

    route:
      app:
        hostnames:
          - profilarr.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      config:
        existingClaim: profilarr-config
      tmp:
        type: emptyDir