---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pulse
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: pulse-secret
    creationPolicy: Owner
    template:
      data:
        # App
        PULSE_AUTH_USER: "{{ .PULSE_AUTH_USER }}"
        PULSE_AUTH_PASS: "{{ .PULSE_AUTH_PASS }}"
        PULSE_ENCRYPTION_KEY: "{{ .PULSE_ENCRYPTION_KEY }}"
        API_TOKEN: "{{ .PULSE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: pulse