---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app filebrowser
spec:
  chartRef:
    kind: OCIRepository
    name: filebrowser
  interval: 30m
  values:
    controllers:
      filebrowser:
        annotations:
          reloader.stakater.com/auto: "true"
          
        containers:
          app:
            image:
              repository: ghcr.io/gtsteffaniak/filebrowser
              tag: 1.1.2-stable@sha256:24b80967bea15d5595c28065146ff7a931f0538c110f34748c037979ef2d634e
            env:
              PORT: &port 80
              FILEBROWSER_CONFIG: "/config/config.yaml"
            envFrom:
              - secretRef:
                  name: filebrowser-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        ports:
          http:
            port: *port

    persistence:
      config:
        type: secret
        name: filebrowser-secret
        advancedMounts:
          filebrowser:
            app:
              - path: /config/config.yaml
                subPath: config.yaml
                readOnly: true
      configdir:
        existingClaim: *app
        globalMounts:
          - path: /config

      shared:
        type: nfs
        server: 10.100.0.81
        path: /safe/shared
        globalMounts:
          - path: /data/shared

      hama:
        type: nfs
        server: 10.100.0.81
        path: /safe/hama
        globalMounts:
          - path: /data/hama

      users:
        type: nfs
        server: 10.100.0.81
        path: /safe/users
        globalMounts:
          - path: /data/users

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    route:
      app:
        hostnames:
          - cloud.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network