apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wzJ+xwvcOgkwol219t3tc2HoQOnlIymkUGnHXZRkWoA=,iv:t1TyBik0Ih5yg1yBZjzyZ9nNJjFfW7yLrCp5YGsmHXY=,tag:QE8JdB+MzkF0JwplQkZdUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2dZbnd0QXNMRGw0SnBJ
            SWthMkxmR2VOQ090ZDlSV3I5a3dBai8zWmtjCnQ4c3A2ZkI0T0tPNHVobkp5dm93
            L3o0MWpNWi9iUUZTcDQvUyswOEV3VHcKLS0tIEl6YlFDQUlBei9XRXhVZURoSThr
            aWU5MWxySFd3OTh6NExQc1FhMGdRYW8KniL/0fYjAOq3UVK4kiIEvsjBQEMQvKVa
            B01Nw1hiaOwHK+02PptG2fAM3oNQ0TYUpNXTNoesFTiYIIxTaNSQWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T10:50:38Z"
    mac: ENC[AES256_GCM,data:LTWkIIT/0nZCslFSvb8C9CUv8B5ALROh1fchu40T5IDKTOOcpbJ2Il4sfB1ao3HPaZ2ZtgupGrAAMaOR3VutKcFGgAoKnBRjsXCnS6NXwNNbsZsex04UR19HSjg7sHowejMRHErPjlJD0y+sg8JyxgJT8sus31FiKAoWq/+mLXo=,iv:3KIVSoj+05HYd8NgKBJEo2Y76UV5yq9i/MxWVoc9afg=,tag:i3TVpwfVdDsq5GwLXgsjxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
