apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0m5RGNGoauMoAQ5YDqzJ8qr+taHT6snhHsd8aDxzPkM=,iv:MIr7ydzxHioO1PD64cbU67LB7w1gpIPWeRBBbiXDA/M=,tag:dbW1eX7e+ybUcOcyiP7+qA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVUNYVzNaNGRSQ3lrZk40
        Ny9Jd3ZCaGMrL1VsanYzU3FCV0IzZ2JnRDFFCnF0bzUwbjluY1pGeGR5bTJMSTh0
        WVBJUWpVZElpTU5ocGlBNURRYjhUT2sKLS0tIEF4Y25yRXZpaDRVNThtZGNRTE41
        aFlDdVd6M3dJOCtoL1doOUpKS3lTM2MK3eR4tWix9E1yv86Xo9xUIkNfiyYOlxWM
        rP7kG2a3TgBuJzopoPHqdIlk30lHKzuiG+a8velKXmokv4UKbmQBEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:06Z"
  mac: ENC[AES256_GCM,data:2DVchhpjXc42DvrvUUt6kXJT0lllVDtNawvl7l90/FkJao/x3RBFyfJ6Sb75zbI6SZCDL7EKzvFt4Aohg3xFknsdQzvQFde51ASD9lZcbMm0aJ76SfU4LNLOhBOVGIg9orXl8BaZtQtIkw0bcZXMI1byGCpPqGe2RtkTcKZIE1s=,iv:CFI8zfU10oWNlOgNyJV6y8qT9EteMlVdDmNJoRDy0Vk=,tag:a8Uqf3LYntRSCx918vHFgA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
