---
ui:
  time_format: 24hour

logger:
  default: info

mqtt:
  enabled: false

auth:
  enabled: false

tls:
  enabled: false

database:
  path: /config/frigate.db

# audio:
#   enabled: True
#   listen:
#     - bark
#     - scream
#     - yell

ffmpeg:
  global_args: -hide_banner
  hwaccel_args: preset-intel-qsv-h264

timestamp_style:
  position: "br"
  format: "%d.%m.%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255

detectors:
  ov_0:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 14

objects:
  track:
    - person
    - dog
  filters:
    person:
      min_area: 3000
      max_area: 100000
      threshold: 0.75
    dog:
      min_area: 1000
      max_area: 10000
      threshold: 0.75

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

go2rtc:
    streams:
        corridor: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.52:554/stream1
        corridor_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.52:554/stream2
        garden_door: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.53:554/stream1
        garden_door_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.53:554/stream2
        living_room: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.54:554/stream1
        living_room_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.54:554/stream2
        living_room_couch: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.57:554/stream1
        living_room_couch_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.57:554/stream2
        garden_chicken: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.51:554/stream1
        garden_chicken_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.51:554/stream2
        garden_carport: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.55:554/stream1
        garden_carport_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.55:554/stream2
        kids_nils: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.56:554/stream1
        kids_nils_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.40.56:554/stream2
        garden_sluice_dining: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.10.117:554/Preview_01_main
        garden_sluice_dining_low: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.10.10.117:554/Preview_01_sub

cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles: [record]

  living_room_couch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room_couch
          input_args: preset-rtsp-restream
          roles: [record]

  corridor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/corridor
          input_args: preset-rtsp-restream
          roles: [record]

  kids_nils:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kids_nils
          input_args: preset-rtsp-restream
          roles: [record]

  garden_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_door
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_door_low
          input_args: preset-rtsp-restream
          roles: [detect]

  garden_chicken:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_chicken
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_chicken_low
          input_args: preset-rtsp-restream
          roles: [detect]

  garden_carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_carport
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_carport_low
          input_args: preset-rtsp-restream
          roles: [detect]

  garden_sluice_dining:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_sluice_dining
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_sluice_dining_low
          input_args: preset-rtsp-restream
          roles: [detect]