---
logger:
  default: info

mqtt:
  enabled: false

auth:
  enabled: false

tls:
  enabled: false

database:
  path: /config/frigate.db

ffmpeg:
  global_args: [-hide_banner, -loglevel, info]
  hwaccel_args: preset-nvidia

detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /config/model_cache/tensorrt/yolov4-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 7

record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

objects:
  track:
    - person
    - bicycle
    - motorcycle
    - car
    - dog

go2rtc:
    streams:
        corridor: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.104:554/stream1
        corridor_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.104:554/stream2
        garden_door: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.108:554/stream1
        garden_door_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.108:554/stream2
        living_room: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.133:554/stream1
        living_room_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.133:554/stream2
        garden_chicken: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.103:554/stream1
        garden_chicken_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.103:554/stream2
        garden_carport: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.134:554/stream1
        kids_nils: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.137:554/stream1
        kids_nils_sub: rtsp://{FRIGATE_CAMERA_USER}:{FRIGATE_CAMERA_PASSWORD}@10.40.200.137:554/stream2

cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    review:
      detections:
        labels: []
    # onvif:
    #   host: 10.40.200.133
    #   port: 2020
    #   user: {FRIGATE_CAMERA_USER}
    #   password: {FRIGATE_CAMERA_PASSWORD}

  corridor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/corridor
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/corridor_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    review:
      detections:
        labels: []
    # onvif:
    #   host: 10.40.200.104
    #   port: 2020
    #   user: ${FRIGATE_CAMERA_USER}
    #   password: ${FRIGATE_CAMERA_PASSWORD}

  garden_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_door
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_door_sub
          input_args: preset-rtsp-restream
          roles: [detect]
    # onvif:
    #   host: 10.40.200.108
    #   port: 2020
    #   user: {FRIGATE_CAMERA_USER}
    #   password: {FRIGATE_CAMERA_PASSWORD}

  garden_chicken:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_chicken
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_chicken_sub
          input_args: preset-rtsp-restream
          roles: [detect]

  kids_nils:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kids_nils
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    review:
      detections:
        labels: []

  garden_carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_carport
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect

    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.65

    zones:
      main-door-person:
        coordinates:
          0.118,0.472,0.42,0.463,0.424,0.165,0.372,0.194,0.37,0.331,0.232,0.329
        objects:
          - person
        inertia: 3
        loitering_time: 0