---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./namespace.yaml
  - ./autopulse/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./jellyfin/ks.yaml
  - ./scrob/ks.yaml
  - ./seerr/ks.yaml
  - ./stash/ks.yaml
components:
  - ../../components/common
  - ../../components/volsync-ns
transformers:
  - ./transformers
