---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kopiur.home-operations.com/privileged-movers: "true"
  name: media
  labels:
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
