---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kguardian
  values:
    controller:
      excludedNamespaces:
        - security
        - kube-system
    broker:
      metrics:
        serviceMonitor:
          enabled: true
    advisor:
      enabled: true
    database:
      persistence:
        existingClaim: ${APP} # PVC created by the volsync component
