---
keys:
  - &user_dominik age1kqazsfpkl7xgu02l5szaq2gutvnwevz69fp9zsp9la7e5shzn5dq7sfwp4

creation_rules:
  - path_regex: clusters/.*/talos/.*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_dominik

  - path_regex: clusters/.*\.sops\.ya?ml$
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - *user_dominik

  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_dominik