apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: external-secrets
  labels:
    type: gcp-credentials
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      "type": "service_account",
      "project_id": "cluster-hama-vault",
      "private_key_id": "a08f423338392be89f4d7a58e49c5b607f35579b",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCDKFWkkXNfpyD2\ntHzEAPMfekZ8OeRl/FAsf5cAhwhZjQdbIsxusvf0mPEu5OvZ/4o6iUr2sgnP1w+f\n6F1we2oAbIZpZjw95N4jK+SIqHYdsS/ougGqMzZUqQRyMGQ0pNUQiIFB99DjUBJM\nGLDgWMEfe3NCS7vVVu3KRI4Uc1OoArmgwJ2h7UOxeYpdmcbGs+enMIdkixC/1Xfd\nulOfY/p1D7PlgR+H+ObftHPFaudvg+DesSY3H8H4mYiZ3rPLNRjAT6sPylSrgFNU\n2OxRX4UYlgt9XsMjV9cboDGGDLuO8XkL/jry6shFXrSKaTYIw3J9AN7oxawAk2YB\ndV7QuZkNAgMBAAECggEAJJlszK+J8ndAy5cx+cAKGA6W/LNq+Mqf1MsF6C/GNLcW\nBmh/g6SNbMQBCYT4C60zdYI6WPz1n/nzcjv1Vx4ZRmUCXQcaaGslUcs9yqS30TFQ\nnTDKpiQEVTuU8ghu7gHRMvvklfQBZm1Brdp2ASTDP3XDhAx+LdpEIN1giHRmM8uo\nnODmlvIB8VEw5HzC0mKmsAQQDyTehqGNQl9Swj574m3WJgmMByz1ye94FqO/6pFh\ngHLbEsFkkoF/4YgRB//OBZ9gq51YgGMzKHwO+aUEEmSMcxD5OaWQxktxcIHdZaZt\nXdUhmMwRMhYoNueOIvjYm6aNMTh3ghGzyoK1X+q0QQKBgQC3pEXaKuPD8RLAHNkv\nLI7is2R6F830xZK7vuEBSAy3ut5iK0SUjWjI4HwQ3YLVuvNVb/Xgw20wAbSx05zX\nyAcxghMEi8GUDiN33wqdz9mtp4sX5WQV3jjkMAgOvR9sglbsP75eEnQ09943zXjr\nlYn2Cb/YRJlvRY350l+su1+rDwKBgQC21gwSpCi7Dr9zuGLenPrJHU4tuxaBuU7G\nXkfkWVbWwpFIfYtaJIs7dvi//iNUePhMeIZ6Ab7JOx7QdfbK/VgmU8ZOHe5EHjTw\nzEUhobgLE01DcfCmZvUk7IsJiGB1sPIUsHElBljfB/e4WxDrkATqIjAasKLR+O64\nKdeoMR9qIwKBgQCAicsa2cpy69pj/c1G57lblJVPoDnYijIal5CGhRfhwjrGG+L0\n18XwVLCCXYmmcCTCOIuxtxhF8eu4TJYLs0bVsGX/WJM2Pm81CDk2HLYQhqUlJLrZ\nU6IelkANkPLd0J1m33cwAVq1eIliJb/tpc3bGRffGKUM7XJi2o19KencoQKBgQCL\nqTNtpeHLCXfrIES9wXG74FvQiOGnU/K9ilUmM6wmvlcV5Xhl8hY85SMcHTfFleYt\nG7+1QNIIitV97S4IXr9P/5wyHaDcfap46cBA8XRRWXwicc2efnTxsJKARKFSJUi1\nzxWOb6vBKifqtf1VwxxN8LGIIbct5xYKrUOjoWpauwKBgQCPygAk3Ue3xWY5q9Fq\n9bZThNlvXeQmx2Lh/NYJPbzEjHjO8apV4LsFvXux335roLkQTsbK6ZYtp0ONKWy+\nLbklHstHdu297x97+u0KjgUS1ESI756g11ZbUB7lX3MD/pfgxY4Aa2UZ2ntawJfd\nG1kO35cQsn06e9piR3ygJWWcxA==\n-----END PRIVATE KEY-----\n",
      "client_email": "external-secrets@cluster-hama-vault.iam.gserviceaccount.com",
      "client_id": "101707060428433893650",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/external-secrets%40cluster-hama-vault.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }
