apiVersion: v1
kind: Pod
metadata:
  name: stash-config-editor
  namespace: media
spec:
  restartPolicy: Never
  containers:
    - name: editor
      image: busybox:stable
      command: ["/bin/sh","-lc","sleep infinity"]
      volumeMounts:
        - name: config
          mountPath: /root/.stash
      # Optional, falls du nicht als root schreiben kannst:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: stash-config