---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  CLUSTER: '{{.CLUSTER | default "gryffindor-prod"}}'
  KUBERNETES_DIR: "{{.ROOT_DIR}}/clusters/{{.CLUSTER}}"
  TALOS_DIR: "{{.ROOT_DIR}}/talos/{{.CLUSTER}}"

env:
  KUBECONFIG: '{{.KUBERNETES_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOS_DIR}}/clusterconfig/talosconfig'

includes:
  bootstrap: .taskfiles/bootstrap
  external-secrets: .taskfiles/externalsecrets
  kubernetes: .taskfiles/kubernetes
  sops: .taskfiles/sops
  talos: .taskfiles/talos
  volsync: .taskfiles/volsync
  workstation: .taskfiles/workstation

tasks:
  default:
    silent: true
    cmd: task --list