---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  CLUSTER: '{{.CLUSTER | default "thestral"}}'
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}"
env:
  KUBECONFIG: '{{.KUBERNETES_DIR}}/kubeconfig'
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'

includes:
  bootstrap: .taskfiles/bootstrap
  external-secrets: .taskfiles/externalsecrets
  kubernetes: .taskfiles/kubernetes
  volsync: .taskfiles/volsync
  workstation: .taskfiles/workstation

tasks:
  default:
    silent: true
    cmd: task --list