apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://git.schwarz47.at/dominik/cluster-hama.git
  ref:
    branch: main