---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-database
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: immich-shared
  path: "./kubernetes/main/apps/selfhosted/immich/database"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-server
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/main/apps/selfhosted/immich/server"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
    - name: external-secrets-stores
    - name: cloudnative-pg-cluster
    - name: immich-valkey
    - name: immich-database
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: immich-data
      VOLSYNC_CAPACITY: 30Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-ml
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/main/apps/selfhosted/immich/machine-learning"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: openebs
    - name: immich-server
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-valkey
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/main/apps/selfhosted/immich/valkey"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true