---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: frigate
  dependsOn:
    - name: ceph-csi-rbd
      namespace: storage
  values:
    controllers:
      frigate:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: frigate-gpu
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.16.3@sha256:cf4305d9f1c673d71c4d0fab30ca56ca05ac91168711a74ee7867a4691a7ad02
            envFrom:
              - secretRef:
                  name: frigate-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: 5000
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 2.0.0.98700m
                memory: 2Gi
                gpu.intel.com/i915: 1
              limits:
                memory: 4Gi
                gpu.intel.com/i915: 1

    service:
      frigate:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.100.10.203
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: 5000
          go2rtc:
            primary: true
            port: 1984
          rtsp:
            port: 8554
          webrtc-tcp:
            port: 8555
            protocol: TCP
          webrtc-udp:
            port: 8555
            protocol: UDP

    persistence:
      media:
        existingClaim: frigate-media
        globalMounts:
          - path: /media

      config:
        existingClaim: frigate-config

      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm
      
      tmpfs:
        type: emptyDir
        advancedMounts:
          frigate:
            app:
              - path: /tmp
                subPath: tmp

    route:
      frigate:
        hostnames:
          - frigate.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network

        rules:
          - backendRefs:
              - identifier: frigate
                port: 5000

      go2rtc:
        hostnames:
          - go2rtc.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network

        rules:
          - backendRefs:
              - identifier: app
                port: 1984