---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: ceph-csi-rbd