---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: hoarder-secret
    template:
      engineVersion: v2
      data:
        encryption_key: "{{ .HOARDER_ENCRYPTION_KEY }}"
        meilisearch_master_key: "{{ .HOARDER_MEILISEARCH_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: hoarder
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "HOARDER_$1"