apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
stringData:
    api-key: ENC[AES256_GCM,data:2CwDd+6w4IeZIMmdvCfGEldRJ72YvS+EL6Vshe6VU58=,iv:Vzu/GaVf8lQUcjzrWbiBp7z6iNznvAY9C4QCt6zjRwE=,tag:YWyBIuelsQ34kSEa3/mFQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqclYwYTNZTnBxVDNhRkYy
            T29rYmtVeXpiS2E4R20zWndYdlhRQVVZTGwwCkxiSzZuYXY2M3IraXRMMlk5ektJ
            QXh3SUVmcWV0VmdMcWtVaXRMdFRlcVUKLS0tIHBiSGhMTmRwRHo4U1RaYjROREZz
            eldVbFFyaEFnY3ZUa2VjMkcvOXoxQTQKBy+aCtqs4EkANos9TbqRgTTr5w1m8cXz
            +Pot8g6P18WbbNwZOkvSxmSkMDQGYL9ZeV3SmUHmtliXZnuJ/zYc8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T23:38:20Z"
    mac: ENC[AES256_GCM,data:TZw0CFVgI40CnaAHvK2h21Jm40hYA4UzE488ruMuB+KywYwS0rBqHBaZjD+q3jEeKs97Yf2ROYYYH/+RpzoDf/hjj1+0ZfblMLmCtOTZ2nVAL6FVd30oZq4rqonhfB3ar3CVk3yDCtrSmDQPBDPnT5Cnu9ShMM35Erfc5jHyu6A=,iv:xx+Vy/Dym8a4VWF6sgJRO32dMhicYArMcU9BYtCphPs=,tag:lZdrEeGifDqxEarizoMhQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
