apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  api-key: ENC[AES256_GCM,data:vnwqMiD52b9p1X/5yl5L6XbBR2ya8vPv/tznYRFyKFs=,iv:PjRkjuITbXnlBCrC1uDuo4Ip+wtuc8Ih5XRASEoXWZ0=,tag:DS+eSvJbzfBuuX/up64wrg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q29PN0dmaHJaZjZNb2ZL
        Y2J2UlI1QW8zVDNFUVg2OHp5cGQ1NjVpcldFCmNEOUpZQ3FXK0haRE8xeFFLTXEz
        V0ttVGQyNk1JdXRFbm96WHZQYTloUkEKLS0tIDNVMjlKaVVHYy9NUElXRjYyUUdj
        RnpSTGhLc1VtYWdBbkhObzF5M2lDaDgKXIhmVwJoxikc60t7UrdQdPqpzCv0yJG7
        6FqCal2LV1lA2A0lzqYnOnXdFzhhZ/TbyxOM6AJnJBejhPriJoAn5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:05Z"
  mac: ENC[AES256_GCM,data:h5iWMkZNrKW9GA21wNp7wKqRMsTB+A3DMgfg8w5Z16YFnxpNz8yPd7No75kOig+WaNfvrXYJmKKVdRxHZI0H0Jtj5YVGr2IQd8TVrYPvov1t7mxYP0veDoaBFpw3N8lhapNz55YeouGOy36rLKGp7TFpQHeY+kOgZcrWsEwsnYc=,iv:vPfh/DdHk4R/rYHbELoz5jDQe+MQg6siwR5ytzWemsA=,tag:kuQsTvszZJ5Q5qquHdIDiw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
