---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama
  namespace: ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
    - name: volsync
      namespace: system
  components:
    - ../../../../components/volsync
  path: "./kubernetes/apps/ai/ollama/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  timeout: 5m
  wait: true
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_NAME: ollama-bootstrap
      VOLSYNC_CAPACITY: 1Gi
