---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: unifi
      version: 0.2.9
      sourceRef:
        kind: HelmRepository
        name: k8sonlab
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      ClassName: internal
      hosts:
        - host: "unifi.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 300m
        memory: 2Gi
