---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name decluttarr-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: *name
    template:
      data:
        config.yaml: |-
          general:
            test_run: false
          jobs:
            remove_failed_imports:
              message_patterns:
                - Not a Custom Format upgrade for existing*
                - Not an upgrade for existing*
          instances:
            radarr:
              - base_url: http://radarr.downloads.svc.cluster.local:7878
                api_key: {{ .RADARR_API_KEY }}
            sonarr:
              - base_url: http://sonarr.downloads.svc.cluster.local:8989
                api_key: {{ .SONARR_API_KEY }}
            whisparr:
              - base_url: http://whisparr.downloads.svc.cluster.local:6969
                api_key: {{ .WHISPARR_API_KEY }}
  dataFrom:
    - extract:
        key: arrs
