---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-relay-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: smtp-relay-secret
    creationPolicy: Owner
    template:
      data:
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_TOKEN }}"
  dataFrom:
    - extract:
        key: smtp-relay
