---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-schwarz47-at
spec:
  secretName: apps-schwarz47-at-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "schwarz47.at"
  dnsNames:
    - "schwarz47.at"
    - "*.schwarz47.at"