---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ./namespace.yaml
  # - ./bookstack/ks.yaml
  - ./immich/ks.yaml
  - ./ocis/ks.yaml
  - ./onlyoffice/ks.yaml
  - ./paperless/ks.yaml
  - ./termix/ks.yaml