ui:
  time_format: 24hour

logger:
  default: info

auth:
  enabled: false

mqtt:
  host: emqx.database.svc.cluster.local
  port: 1883
  topic_prefix: frigate
  user: "{{ .MQTT_USERNAME }}"
  password: "{{ .MQTT_PASSWORD }}"

database:
  path: /config/frigate.db

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: []
  output_args:
    record: preset-record-generic-audio-aac
    detect: -f rawvideo -pix_fmt yuv420p

detectors:
  ov_0:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

detect:
  enabled: true
  fps: 5

lpr:
  enabled: true
  format: "^[A-Z]{2} [0-9]{3}[A-Z]{2}$"

snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 14

objects:
  track:
    - person
    - car
    - dog

review:
  alerts:
    labels:
      - car
      - person
  detections:
    labels:
      - person
      - car

record:
  enabled: true
  continuous:
    days: 3
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 14
      mode: active_objects

go2rtc:
  streams:
    corridor: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.143:554/stream1
    corridor_low: 
      rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.143:554/stream2
    living_room: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.136:554/stream1
    living_room_low: 
      rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.136:554/stream2
    # living_room_couch: 
    #   rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.57:554/stream1
    # living_room_couch_low: 
    #   rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.57:554/stream2
    kitchen: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.127:554/stream1
    kitchen_low: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.127:554/stream2
    garage: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.119:554/stream1
    garage_low: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.119:554/stream2
    sluice: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.140:554/stream1
    sluice_low: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.140:554/stream2
    garden_door: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.123:554/stream1
    garden_door_low: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.123:554/stream2
    garden_chicken: 
      rtsp://admin:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.114:554
    garden_chicken_low: 
      rtsp://admin:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.114:554/h264Preview_01_sub
    garden_carport: 
      rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.118:554/stream1
    garden_carport_low: 
      rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.118:554/stream2
    # kids_nils: rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.56:554/stream1
    # kids_nils_low: 
    #   rtsp://camera:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.56:554/stream2
    garden_garden: 
      rtsp://admin:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.124:554
    garden_garden_low: 
      rtsp://admin:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.124:554/h264Preview_01_sub
    garden_sluice_dining: 
      rtsp://admin:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.146:554
    garden_sluice_dining_low: 
      rtsp://admin:{{ .FRIGATE_CAMERA_PASSWORD }}@10.10.40.146:554/h264Preview_01_sub
  webrtc:
    candidates:
      - 10.100.10.203:8555
      - stun:8555
    ice_servers:
      - urls:
         - stun:stun.cloudflare.com:3478

cameras:
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/living_room
          input_args: preset-rtsp-restream
          roles: [record]
    live:
      streams:
        Main Stream: living_room
    detect:
      enabled: false

  corridor:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/corridor
          input_args: preset-rtsp-restream
          roles: [record]
    live:
      streams:
        Main Stream: corridor
    detect:
      enabled: false

  kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles: [record]
    live:
      streams:
        Main Stream: kitchen
    detect:
      enabled: false

  sluice:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sluice
          input_args: preset-rtsp-restream
          roles: [record]
    live:
      streams:
        Main Stream: sluice
    detect:
      enabled: false

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garage_low
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams:
        Main Stream: garage
    objects:
      track:
        - person
        - car

  # kids_nils:
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/kids_nils
  #         input_args: preset-rtsp-restream
  #         roles: [record]
  #   detect:
  #     enabled: false

  garden_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_door
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_door_low
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams:
        Main Stream: garden_door
    objects:
      track:
        - person
    lpr:
      enabled: false

  garden_chicken:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_chicken
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_chicken_low
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams:
        Main Stream: garden_chicken
    objects:
      track:
        - person
    lpr:
      enabled: false

  garden_carport:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_carport
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_carport_low
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams:
        Main Stream: garden_carport
    objects:
      track:
        - person
    lpr:
      enabled: false

  garden_garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_garden
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_garden_low
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams:
        Main Stream: garden_garden
    objects:
      track:
        - person
    lpr:
      enabled: false

  garden_sluice_dining:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garden_sluice_dining
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/garden_sluice_dining_low
          input_args: preset-rtsp-restream
          roles: [detect]
    live:
      streams:
        Main Stream: garden_sluice_dining
    objects:
      track:
        - person
    lpr:
      enabled: false

version: 0.16-0
