---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app frigate
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: ./clusters/thestral/apps/home-automation/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: ceph-csi
      namespace: storage
  components:
    - ../../../../components/gpu
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: frigate-config
      VOLSYNC_CAPACITY: 5Gi