---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: zitadel-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        masterkey: "{{ .MASTERKEY }}"
        # Postgres Init
        ZITADEL_DATABASE_POSTGRES_DATABASE: "{{ .POSTGRES_DB }}"
        ZITADEL_DATABASE_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        ZITADEL_DATABASE_POSTGRES_USER_USERNAME: "{{ .POSTGRES_USER }}"
        ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: zitadel
    - extract:
        key: cloudnative-pg