apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:7NjBC0uzI2A5oddGHKLd0s7yQ27EpVPIu5IQcCm7qBfYIke9,iv:UtAAe8P25PMtgvzwkblATNEZpQdI6NPZAYwXkqALIUw=,tag:GxnNjPLG+iAkvAKrHWXXxw==,type:str]
    credentials.json: ENC[AES256_GCM,data:nmb6+184JolCghyuowFKbcn0aO1u0XEp4/bkjGKPlbULeatlzIG4ehFNv9Z9L0LshXKbsouC/V849UCwD6MBmJexx/S8vhYpoDOQi3PJQGIZgTUHcm4VFqQPJ5SPDG9nLujjUXcgxJFpw/OpScc6bdNTGvDBedDOjokJ3Xjdjsag3BBt2kAkVowukbE1dhgJ/qrIHtTCAaSpZ8qntLwLBTTBw+/C7D+hjSo9wemUrQ==,iv:BZGFJojDd8SdidonzyFJq+YVlxwuOIaUOHIrObcjnrM=,tag:33ldyYoRcFsofFSUpxYaWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rnp5c6u2cgdp8zm5cjg33nux8fql2epjumzxqe7gw5lpsnx9djsh6qxy2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTmhHK1Z4bmN5bjM0Um1v
            dUtxbXZaTGxNZWZnczFsT0xNdXdpejdIaXhFCnVmYm5SdjFvblJEaUs5UkxOOXNM
            U21Vak1HaFo0VVhFMVZIblJTRkdyMzQKLS0tIFByZmZWQXZNZ01WT1pMYkxJbVRo
            TWZmeG04UWN5aE8rWUZvOTh4WldUY0EKubjh+83IML/QkKIazSXRM00dOJMJvAfW
            /eesRQGcE6JEdhLX1awk5Xt0ZFxD6EumE81iGpCYjcgXHYMhF8XLqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T22:05:42Z"
    mac: ENC[AES256_GCM,data:4nuHGeb+5KLwYE8kprrUHLJSCq8x2hqnamQ5XRsEuyrgxsBev01RmEVjZ9R6C8ImyXUNu20xSJiLFRsI3TVsEryuVtuCoUlsKQVck6GybengAx/Sdr+pU9WsRE7YEOXXLK1ifg9+qlyoKollJO13ioycwqVIm3ltHdoL1u4lxSI=,iv:JibgZzsMvpGCvW4iV/XoD0YGX4mVgZ8K3UyEn+Nv/R0=,tag:wz4rDBBYZF+lNYq8h7c1sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
