apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UnkpoUL7fUepau9VRYMWRneOFTjPJnVm8JrWoLwdTFyGWlsS,iv:e81LDMcJ1eOa8m6duf7KIK45gfIQhOLTCB1bPlbSIBs=,tag:clFeqpAiXxyUechEJHY+vA==,type:str]
    credentials.json: ENC[AES256_GCM,data:Ppd+7+gY4jw0g/JKCmgv6jvX91RTw33WFe46+I8NbR1lsdZRlprcR1nLCMv3+CDZ/39wqxzpEbHgR3CZLhSMwrhTPDCUU4VJi9ztslD0ciBbHp/rotQz5puE8Ob3HTF0Xg8S+nJXtYdhL0aQwO/5Y809yI/EGZ8uElOnBEYOlwKBOkxm436baUQqlXbk5sBL8P9++L1Utxwo1t8ts4U33+Hsvqjw2eDzLN89crSyNQ==,iv:NB1Knfo2/m9pbbmaD5sTM63HopKF3GHGysPeCbbhI6s=,tag:ZJaxHbiF8xYDdb00amDAhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVjJKS2F2MnNtYmF6ak5n
            UWFqS05DSmZGNHBHZlRrVXBzM2M5eWp0NXlvCjBOY3NvR0N5b3ZRVGdWZy8vZmcv
            SXpWTUN3VWFGdmduOEZIRWpaenpZSzAKLS0tIGh6b0V2bk1ibDBENVp5Q0JyNTNU
            cnFVdis4RFhuWWZocitLbmJQTXR0NVkK2Rt0uQDwLFhfnt/2Be1Ugq4kBwOOj/MB
            oPjVVgjjdpn/qe6NTUMXJouX5yw02ovzFEChBlrowuLOSenXDeW1Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T22:34:22Z"
    mac: ENC[AES256_GCM,data:vDtXXRqahtTt+lCpNSkS/Yo3kxYC9mEl22OxBSnBxH36t5VJUxcrQYp1IECvUQLmibiTXHlNlgcwDzE0q9j4AjcdnJJLi3AEMw2c7GnuDq6Rh+cR92jalyLRdmHUA8h0U0+agDH9+AfVl5EvY77oR1aGDgiY9ssirq1QFViQvj0=,iv:7v1zKedW8lkxS1VqeiIQn6fhU3tbsZZDVY0Gwh/0GbY=,tag:dqn1OvYuEcXjKf5r1Peo7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
