apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:L8v6lXtPECk4qwIwNzDzheX3tZFgFDGmwInfPS5iXmwWPoCp,iv:KnsAq22jKeHUFQ5xj2zyVlxOSKlqpjv5cery6XEngWg=,tag:oJdQyAlmEse9lB0LJnipPg==,type:str]
    credentials.json: ENC[AES256_GCM,data:QciPthWvAZCXYrZPjOwm/PDkZAaD2pyFx7xGnnhbO6aV9Vx9xlafeBX+Ndo+8CpvA7Asnk72ElChl3KF6K/37LIzcRX9DdIycC6wyGkC0vvkEvl3X7alBm8tn05ekMS6XCJ6+Y27tknwfr70tdOS/LuEy31GDz/9hxuqKnp/WO7z4XFITI4803T2aHmgB0raPLbeeoExOcvc8VMJTcA25TuIEYzXLGKXOMco96b9Zg==,iv:aRJlntD8vHXcluvyGXrRr802dp7Kq134wDnhRX/egGM=,tag:PCFu/OIqxokM0rA3AVf47g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSEw1ejY5OFFGUUMydXdQ
            VlB5RU8wV2x2aVF3RWZzRkJvbWc0d0VqS0FzCkwvRDFOOXZkWlZ6ODN5MUVwWndL
            TVJKNG5GWlVDNVB6WG9oRFU3bjAzSDQKLS0tIENDU3A2ek1vaEN0T1VsY0hPcUll
            UzZZbVhUL1NOT2pSZVp5SGZ5K3hWRmsKWiMj5jszE7jaWy0bD7vJQEKap+usdxzn
            Aj2469vXd28M2GjFw3Z0MDNxYA22wlvwMqh5M12M0KKihSCQ05Ri3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T23:05:54Z"
    mac: ENC[AES256_GCM,data:X1byg1GLhrCzCBUm0V5pdee9tqjUYTsl9qWmE2BKJWfVxWU78IuwEWgTRYGIkJuQu0qIQW19cPVbQUNdQCLL18t9jnp7xW5lI2/N0bbSyxFYBcAqGHrFe5bOBppCs9bWo06uAhemesBuGoF8rK0O1BKJGgEKqObRQNn7yY1KZss=,iv:VWiPo9kBXc7bna5DvbSNgAASW7OzL4SqfdBgkZKNmXw=,tag:y/UGbjW2PD+hbC19+pUuwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
