---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authelia-to-media
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: media
  to:
    - group: ""
      kind: Service
      name: authelia
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1beta1.json
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authelia-to-monitoring
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: monitoring
  to:
    - group: ""
      kind: Service
      name: authelia