---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ./bentopdf/ks.yaml
  - ./immich/ks.yaml
  - ./collabora/ks.yaml
  - ./it-tools/ks.yaml
  - ./kroki/ks.yaml
  - ./obsidian/ks.yaml
  - ./outline/ks.yaml
  - ./oxicloud/ks.yaml
  - ./paperless/ks.yaml
  - ./redlib/ks.yaml
  - ./termix/ks.yaml
  - ./vikunja/ks.yaml
  - ./namespace.yaml
components:
  - ../../components/common
