---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    pod-security.kubernetes.io/enforce: &ps privileged
    pod-security.kubernetes.io/audit: *ps
    pod-security.kubernetes.io/warn: *ps