---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore
  kopia:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
    capacity: "${VOLSYNC_CAPACITY:-5Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    repository: ${APP}-volsync-secret
    sourceIdentity:
      sourceName: ${APP}
    storageClassName: "${VOLSYNC_STORAGECLASS:-csi-rbd-sc}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-rbd-snapclass}"