---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-versity
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 * * * *"
  kopia:
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    compression: zstd-fastest
    copyMethod: Snapshot
    parallelism: 2
    repository: ${APP}-volsync-versity
    storageClassName: "${VOLSYNC_STORAGECLASS:-csi-rbd-sc}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-rbd-snapclass}"
    retain:
      hourly: 24
      daily: 7
      weekly: 4
      monthly: 12
