---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whisparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: whisparr-secret
    creationPolicy: Owner
  data:
    - secretKey: WHISPARR__AUTH__APIKEY
      remoteRef:
        key: arrs
        property: WHISPARR__API_KEY