apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      whisparr:
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 5000
            runAsNonRoot: true
            fsGroup: 5000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/jfroy/whisparr-nightly
              tag: 2.0.0.787@sha256:15b02a8ebf60b26bf55f8a6b5583389fb4a1b17eb15e5025cb75972a210be1dc
            env:
              WHISPARR__APP__INSTANCENAME: Whisparr
              WHISPARR__APP__THEME: dark
              WHISPARR__SERVER__PORT: &port 6969
              WHISPARR__AUTH__METHOD: External
              WHISPARR__AUTH__REQUIRED: DisabledForLocalAddresses
              WHISPARR__LOG__LEVEL: info
              WHISPARR__BRANCH: nightly
            envFrom:
              - secretRef:
                  name: whisparr-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: whisparr
        ports:
          http:
            port: *port

    route:
      app:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: network
        hostnames:
          - whisparr.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: app
                port: *port

    persistence:
      config:
        existingClaim: whisparr-config
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 10.10.200.50
        path: /mnt/storage/media
        globalMounts:
          - path: /data/media
