apiVersion: v1
kind: Secret
metadata:
    name: whisparr-secret
stringData:
    api-key: ENC[AES256_GCM,data:it4JIJJOnBkd3qw2PIsqcDrENrLaaVlozs0GP/bs5yo=,iv:mZAR6MCvtXKgqu4qfGarYbgyAbr3z/FJUhSD+mAY6w0=,tag:dDcX3idoKdadK51BVEZOyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqclYwYTNZTnBxVDNhRkYy
            T29rYmtVeXpiS2E4R20zWndYdlhRQVVZTGwwCkxiSzZuYXY2M3IraXRMMlk5ektJ
            QXh3SUVmcWV0VmdMcWtVaXRMdFRlcVUKLS0tIHBiSGhMTmRwRHo4U1RaYjROREZz
            eldVbFFyaEFnY3ZUa2VjMkcvOXoxQTQKBy+aCtqs4EkANos9TbqRgTTr5w1m8cXz
            +Pot8g6P18WbbNwZOkvSxmSkMDQGYL9ZeV3SmUHmtliXZnuJ/zYc8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T00:08:52Z"
    mac: ENC[AES256_GCM,data:cl1JI7qtFA+45ZqiQ2IAwOXTY4p+eOE2QhYvf+xNOO/erxz5ALlkN8dKnMUHQf9Zq5yqFSIyWz36c156wpQWEOWBCoJjT3jsMiG/1cDdr/A4snlD76UVl201uaVcfk5tPc6yGssPtZBCIezyifzQzFEqMb7k/8TN4GVSNSLABUg=,iv:4fDrKun5sV9NiEzdI1fflTeBF2pkS/nCKAirnaDDWKM=,tag:ALexMtzAEw97lpm6IOu1WQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
