---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chart:
    spec:
      chart: frigate
      version: 7.6.0
      sourceRef:
        kind: HelmRepository
        name: blakeblackshear
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    persistence:
      config:
        enabled: true
      media:
        enabled: true
        size: 10Gi
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: "frigate.${SECRET_DOMAIN}"
          paths:
            - path: /
              portName: http
    config: |
      mqtt:
        enabled: false
      auth:
        enabled: false
      tls:
        enabled: false

      # ffmpeg:
      #   hwaccel_args: preset-intel-qsv-h264 -qsv_device /dev/dri/renderD129

      go2rtc:
          streams:
              corridor: rtsp://camera:T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw@10.40.200.104:554/stream1
              garden_door: rtsp://camera:T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw@10.40.200.108:554/stream1
              living_room: rtsp://camera:T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw@10.40.200.103:554/stream1
              garden_chicken: rtsp://camera:T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw@10.40.200.116:554/stream1
          webrtc:
            candidates:
              - 192.168.1.24:8555
              - stun:8555

      cameras:
        living_room:
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/living_room
                input_args: preset-rtsp-restream
          onvif:
            host: 10.40.200.105
            port: 2020
            user: camera
            password: T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw
        corridor:
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/corridor
                input_args: preset-rtsp-restream
          onvif:
            host: 10.40.200.104
            port: 2020
            user: camera
            password: T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw
        garden_door:
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/garden_door
                input_args: preset-rtsp-restream
          onvif:
            host: 10.40.200.108
            port: 2020
            user: camera
            password: T6YedouFE*pvt*uUTQkVBH_kiqKrqwMw
        garden_chicken:
          ffmpeg:
            inputs:
              - path: rtsp://127.0.0.1:8554/garden_door
                input_args: preset-rtsp-restream
      version: 0.14

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 4000m
        memory: 2000Mi
