---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: litellm-secret
    creationPolicy: Owner
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .MASTER_KEY }}"
  dataFrom:
    - extract:
        key: litellm
