---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app versity
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: versity
  install:
    crds: CreateReplace
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    crds: CreateReplace
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/versity/versitygw
              tag: v1.2.0@sha256:09ea9d2acb34e1a597814dac686b0d28d4e69c0a9d5244b63a220a7ace801bf1
            args: ["posix", "/data"]
            env:
              VGW_HEALTH: /healthz
              VGW_WEBUI_PORT: ":7071"
              VGW_CORS_ALLOW_ORIGIN: "*"
            envFrom:
              - secretRef:
                  name: versity-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7070
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 20Mi
              limits:
                cpu: 500m
                memory: 100Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        ports:
          http:
            port: *port
          ui:
            port: 7071

    route:
      app:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - versity.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                identifier: app
                port: *port

    persistence:
      data:
        existingClaim: s3-data
        globalMounts:
          - path: /data