---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopia
spec:
  chartRef:
    kind: OCIRepository
    name: kopia
  interval: 30m
  values:
    controllers:
      kopia:
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/kopia
              tag: 0.22.3@sha256:17ab64542280197a5368247deaefadc3e3bbe15714ab666c2455a06824e86efd
            env:
              KOPIA_WEB_ENABLED: true
              KOPIA_WEB_PORT: &port 8080
              KOPIA_S3_FORCE_PATH_STYLE: "true"
            envFrom:
              - secretRef:
                  name: kopia-secret
            args:
              - shell
              - -c
              - |
                # Falls noch keine Config existiert, verbinde mit S3
                if [ ! -f /config/repository.config ]; then
                  kopia repository connect s3 \
                    --bucket=k8s-cluster-nexus-prod \
                    --endpoint=${AWS_S3_ENDPOINT} \
                    --prefix=volsync/ \
                    --password=${KOPIA_PASSWORD}
                fi
                # Starte den Server
                kopia server start --insecure --address=0.0.0.0:8080 --without-password --config-file=/config/repository.config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
    route:
      app:
        hostnames:
          - kopia.ds47.dev
        parentRefs:
          - name: kgateway-internal
            namespace: network