---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-technitium
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: externaldns-technitium-secret
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: "{{ .EXTERNAL_DNS_SECRET }}"
  dataFrom:
    - extract:
        key: externaldns-technitium