---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ./autopulse/ks.yaml
  - ./decluttarr/ks.yaml
  - ./deduparr/ks.yaml
  - ./lidarr/ks.yaml
  - ./profilarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./whisparr/ks.yaml
  - ./namespace.yaml
components:
  - ../../components/common
