apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-minio
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:+hQIiBGHZbx2XuzSwUs6hWnzdvlgUv+3lnk5B9cJQL93,iv:bWuueci5i5S3P68JSJdxHj2OfNrFtCFfuqgfxHfeAks=,tag:6GjVkYVBpotdIsa0YP16pA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:e0PgfNUlSRtpK/mcgTel1Zn+hgS3rA==,iv:j3+Vegn+FZP74uKr62X2+JHVT9+QVkFYDmk2K5+I0Os=,tag:kB3HDOndHrGMv+eYNI9G4w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YOCmL5xXPG2LknzR7S7BWGbs1ATtOYQN,iv:M+3OEQlM6vDT12LSbsPS0M9cW7MM3QeC+fuoFhjyvw8=,tag:vVNvZaHcJOB6vzn/Ct1ciQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3Unykckpi6fn0lQLv7BomnLyf6lxN0M+uOZZ5w==,iv:XmSOJcV5pSUYpj5F4oBuZZeCG07f9FVJZYjgVrp/gi4=,tag:T0zAUBWDeN2LlLB+8qP60A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTkIvd0c0ZEdWRVE0akVO
        aVVUcEo5cXRYTHo4SmRIMWh4YjJyUE1nMEU0CmR4bFpwRkdhcmRvdWNsVnIyZ1gy
        VzNDYTkveEFVMWExdmFvaHh6YTdmY00KLS0tIHlTWFZxNGRsZ1pTL3dZVnlTQ0Fa
        SS9UYnluNXNFQ3pRcmd5SkEyVTlXNlkK8tZtAu+wX2DyKRSRr++gDTPewP1gVTaK
        b94G5daLPmXvn+x93m0VNgvO4HTrtcbH0FDDrrHtfk95YbXcV3vqFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-24T14:52:24Z"
  mac: ENC[AES256_GCM,data:hrf+ey1QB07VaZmfIfSyPjr/p1WFVIWWK9R2GkW7DDmUVWNKAFyu9bg/8AOuJs8OShAtsi9JbsibiKyk8w+4PG/74WteqK4NwDn8FnyqQYOs8AG/DwUWelVclPVjvFjCBExmh9DcckJJliilY+yZWYTBKyigItWLsLAY0POdaSE=,iv:Ro0RYYjfkxFb6+oiVksNCeGD1phnFmbRXDmw2SLbLMk=,tag:S6Za+l9h6oWSgZfAdlXTgA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
