apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-minio
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:mo0Odj1d47sHvhKOTFvzDcxDJQRYsCniuqlnPnw7+fEX5TEHeYCMwZk0WvRaIAaRfNrQUu59,iv:3KsDiAjYr0SJ3O9tgh7Vr3PSUuNbwLoxpENinrtg1Wo=,tag:ml9XU97HmFIZAe5jXLlhwg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:JXTjMkl0mV6Nl0c0HJJEHfutL/tNznF4II40/2rMHynRS+eI0LkoUmjLV1I=,iv:D5+Vo5AT1dPZja9dYlBp4n/LuA0swk1XE1w4wXHBad8=,tag:LPw4pJIkQobj3lmJi3eRjg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/tDNEGp1O4bd2IX7ZUwQszLiiivR4h2j+0k=,iv:gb1QRRK/3K55lNtG2R5b4EYndI449ZgOiwaLIOoXICg=,tag:kE9IY1xQ9HgzQN4L3P8U8g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JsioUAp5KUV/I4ed/PEzGFPuKhS5NVEMwKANTwnpwhDbDVa7Y6fAd3pEf+LcM6gNZpj41q6j4OLjevnTNYJtfQ==,iv:4gwCF3G9hM/zjW3BLtQH1V3XzGAbvk1c8Z+d6LXP24g=,tag:dNGLXFrl0IQ8gtJsMhEVgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTkIvd0c0ZEdWRVE0akVO
            aVVUcEo5cXRYTHo4SmRIMWh4YjJyUE1nMEU0CmR4bFpwRkdhcmRvdWNsVnIyZ1gy
            VzNDYTkveEFVMWExdmFvaHh6YTdmY00KLS0tIHlTWFZxNGRsZ1pTL3dZVnlTQ0Fa
            SS9UYnluNXNFQ3pRcmd5SkEyVTlXNlkK8tZtAu+wX2DyKRSRr++gDTPewP1gVTaK
            b94G5daLPmXvn+x93m0VNgvO4HTrtcbH0FDDrrHtfk95YbXcV3vqFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-24T22:14:41Z"
    mac: ENC[AES256_GCM,data:u9oBvfZH0ZPhtf20e4N5QpXSmRmmyOYjs8F52JvVJyRL+8z0S25GmfQTx3ZFjb1u5l4fQ3puaW9PZEpKsJOJorrWs9ZTlF/f7fxS0Q86Ft58V1ZPdVpAZKCIqYsYCF4zUWzxCBBBcpc+aR6IpTRrLGaEq2xg+FQrC2+btfXSz8s=,iv:r//d6T8y5Wq/YnjxgK3PbKLYWQt/b7XFf5VRm6LHmco=,tag:c3fd25MmzCuatCtO/xgHfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.1
