---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.2.0@sha256:ae89578925b480f5972f237dda2f7a37efe36aff500d3e7bd1d3a6a3181e4191
            envFrom:
              - secretRef:
                  name: immich-db
              - secretRef:
                  name: immich-initdb
        containers:
          server:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.5.6@sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a
            env:
              IMMICH_MEDIA_LOCATION: &mediaLocation /library
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning.services.svc.cluster.local:3003"
              IMMICH_WORKERS_INCLUDE: api
              IMMICH_TELEMETRY_INCLUDE: all
              # Prevent NFS mount check failures
              IMMICH_IGNORE_MOUNT_CHECK_ERRORS: "true"
              # Redis
              REDIS_HOSTNAME: "dragonfly.database.svc.cluster.local"
              REDIS_DBINDEX: "1"
            envFrom: &envFrom
              - secretRef:
                  name: immich-db
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &port 2283
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: false
            securityContext: &csc
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4Gi

      machine-learning:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          machine-learning:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.5.6@sha256:b213fa3c82d27a21a299c46ffbb38a091f18384db1ad67d409a3b34fe0fce556
            env:
              MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL: ViT-SO400M-16-SigLIP2-384__webli
              MACHINE_LEARNING_PRELOAD__CLIP__VISUAL: ViT-SO400M-16-SigLIP2-384__webli
              MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__RECOGNITION: buffalo_l
              MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__DETECTION: buffalo_l
              MACHINE_LEARNING_CACHE_FOLDER: "/cache"
            securityContext: *csc
            envFrom: *envFrom
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 8Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlPort 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 3003
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 120
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: immich-gpu

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      server:
        controller: server
        ports:
          http:
            port: *port
          metrics-api:
            port: 8081
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: *mlPort

    serviceMonitor:
      server:
        serviceName: server
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics

    route:
      app:
        hostnames:
          - ${APP_SUBDOMAIN:-${APP}}.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: server
                port: *port

    persistence:
      geocoding-dump:
        type: emptyDir
        advancedMounts:
          server:
            server:
              - path: /usr/src/app/.reverse-geocoding-dump
      library:
        type: nfs
        server: 10.100.0.81
        path: /photos
      initdb:
        type: configMap
        name: immich-initdb
        advancedMounts:
          server:
            init-db:
              - path: /initdb
      model-cache:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: csi-rbd-sc
        size: 50Gi
        advancedMounts:
          machine-learning:
            machine-learning:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache
      tmpfs:
        type: emptyDir
        medium: Memory
        sizeLimit: 32Mi
        advancedMounts:
          machine-learning:
            machine-learning:
              - path: /.config
                subPath: machine-learning/.config
      transformers-cache:
        type: emptyDir
        advancedMounts:
          server:
            server:
              - path: /usr/src/app/.transformers_cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
