---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: immich-secret
          configmap.reloader.stakater.com/reload: immich-configmap
        pod:
          enableServiceLinks: false

        initContainers:
          init-db:
            envFrom: &dbEnvFrom
              - secretRef:
                  name: immich-secret
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
            env:
              IMMICH_CONFIG_FILE: /config/immich-config.yaml
              IMMICH_MEDIA_LOCATION: &mediaLocation /library
              IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning.services.svc.cluster.local:3003"
              # Prevent NFS mount check failures
              IMMICH_IGNORE_MOUNT_CHECK_ERRORS: "true"
              DISABLE_REVERSE_GEOCODING: "true"
              # Redis
              REDIS_HOSTNAME: &redisHost "dragonfly.database.svc.cluster.local"
              REDIS_DBINDEX: &redisDB "1"
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4Gi

      machine-learning:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: immich-gpu

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.3.1@sha256:379e31b8c75107b0af8141904baa8cc933d7454b88fdb204265ef11749d7d908
            env:
              REDIS_HOSTNAME: *redisHost
              REDIS_DBINDEX: *redisDB
              MPLCONFIGDIR: "/cache/matplotlib"
              # ML cache folder paths
              MACHINE_LEARNING_CACHE_FOLDER: "/cache"
              TRANSFORMERS_CACHE: "/cache"
              IMMICH_MEDIA_LOCATION: *mediaLocation
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            envFrom: *envFrom
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlPort 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *mlPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 60

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
          metrics-api:
            port: 8081
          metrics-ms:
            port: 8082
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: *mlPort

    route:
      app:
        hostnames:
          - photos.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: server
                port: *port

    serviceMonitor:
      server:
        enabled: true
        serviceName: server
        endpoints:
          - port: metrics-api
            scheme: http
            path: /metrics
          - port: metrics-ms
            scheme: http
            path: /metrics

    persistence:
      config:
        type: secret
        name: immich-secret
        advancedMounts:
          server:
            app:
              - path: /config/immich-config.yaml
                subPath: immich-config.yaml
                readOnly: true

      matplotlib:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /config/matplotlib

      library:
        type: nfs
        server: 10.100.0.81
        path: /photos
        advancedMounts:
          server:
            app:
              - path: *mediaLocation

      cache:
        type: persistentVolumeClaim
        existingClaim: immich-ml-cache
        advancedMounts:
          machine-learning:
            app:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers