---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false

        initContainers:
          init-db:
            envFrom: &dbEnvFrom
              - secretRef:
                  name: immich-secret
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
            env:
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
            envFrom: &envFrom
              - configMapRef:
                  name: immich
              - secretRef:
                  name: immich-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4Gi

      machine-learning:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          enableServiceLinks: false

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.3.1@sha256:379e31b8c75107b0af8141904baa8cc933d7454b88fdb204265ef11749d7d908
            env:
              MPLCONFIGDIR: "/config/matplotlib"
              IMMICH_MEDIA_LOCATION: *mediaLocation
            envFrom: *envFrom
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4Gi

      valkey:
        containers:
          app:
            image:
              repository: docker.io/valkey/valkey
              tag: 9.0.1-trixie

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"

    service:
      server:
        controller: server
        ports:
          http:
            port: &port 2283
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      valkey:
        controller: valkey
        ports:
          http:
            port: 6379

    route:
      app:
        hostnames:
          - photos.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: server
                port: *port

    configMaps:
      config:
        data:
          # URLS
          IMMICH_SERVER_URL: http://immich-server.services.svc.cluster.local:2283
          IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.services.svc.cluster.local:3003
          PUBLIC_IMMICH_SERVER_URL: https://photos.schwarz47.at
          # SETTINGS
          DISABLE_REVERSE_GEOCODING: "true"
          ENABLE_MAPBOX: "false"
          LOG_LEVEL: log
          NODE_ENV: production
          UPLOAD_LOCATION: /usr/src/app/upload
          # REDIS
          REDIS_HOSTNAME: "immich-valkey.services.svc.cluster.local"
          REDIS_PORT: "6379"

    persistence:
      matplotlib:
        type: emptyDir
        advancedMounts:
          server:
            main:
              - path: /config/matplotlib

      library:
        type: nfs
        server: 10.100.0.81
        path: /photos
        advancedMounts:
          server:
            app:
              - path: /usr/src/app/upload

      cache:
        type: persistentVolumeClaim
        existingClaim: immich-ml-cache
        advancedMounts:
          machine-learning:
            app:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache

      tmpfs:
        type: emptyDir
        advancedMounts:
          server:
            app:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers