---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hermes-agent
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: kopiur
      namespace: system
    - name: litellm
      namespace: *namespace
    - name: searxng
      namespace: *namespace
    - name: pocket-id-instance
      namespace: security
  components:
    - ../../../../components/kopiur
  postBuild:
    substitute:
      APP: *app
      APP_UID: "10000"
      APP_GID: "10000"
  interval: 30m
  path: ./kubernetes/apps/ai/hermes-agent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  timeout: 5m
