---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      data:
        # n8n
        N8N_ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        DB_POSTGRESDB_DATABASE: &database n8n
        DB_POSTGRESDB_PORT: "5432"
        DB_POSTGRESDB_HOST: &host postgres-rw.database.svc.cluster.local
        DB_POSTGRESDB_USER: &user "{{ .POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: &password "{{ .POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *database
        INIT_POSTGRES_HOST: *host
        INIT_POSTGRES_USER: *user
        INIT_POSTGRES_PASS: *password
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
