---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      data:
        # n8n
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: n8n
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
