---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: RUNNER_NAME
      remoteRef:
        key: forgejo
        property: FORGEJO_RUNNER_NAME
    - secretKey: RUNNER_TOKEN
      remoteRef:
        key: forgejo
        property: FORGEJO_RUNNER_TOKEN