---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deployment:
      envoyGateway:
        image:
          repository: docker.io/envoyproxy/gateway
          tag: v1.4.1@sha256:e5caac1557603bf3284efb2a3b58b6c28576949cabf0adb81bd0c2e7962a74aa