---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM:-${APP}}"
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}-bootstrap"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-5Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-csi-rbd-sc}"
