---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: oxicloud
spec:
  name: OxiCloud
  launchUrl: https://cloud.ds47.dev
  callbackUrls:
    - https://cloud.ds47.dev/api/auth/oidc/callback
  secret:
    name: oxicloud-secret
    keys:
      clientID: OXICLOUD_OIDC_CLIENT_ID
      clientSecret: OXICLOUD_OIDC_CLIENT_SECRET
      issuerUrl: OXICLOUD_OIDC_ISSUER_URL
