---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oxicloud-data
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.100.0.81
    path: /safe/apps/oxicloud
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxicloud-data
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: oxicloud-data
  storageClassName: ""
