apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZvgrRqHPyafFfDWuPh+rTiayn8m3r2NSxyO7oFEl9LdoNQbd351aeg==,iv:bx2jK2fUhLxZpoCOs5xUiJ2tlgEOh0AQ5zTH8nlmbeU=,tag:J4dBq0Sk/+mMkD93rxufBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rnp5c6u2cgdp8zm5cjg33nux8fql2epjumzxqe7gw5lpsnx9djsh6qxy2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOXhJeHJNY1V6MDdwMGU2
            MXJiNFkreWJCei9uOWJyZDRkM0l2Q1VpKzN3Ci9USzNXQno4d1ZNOGwxS2VON3ZH
            OUxRRzU1alRGSUhOczhtQTYwM0N5Qm8KLS0tIHYzT2xGNGhFemszT1FrejEwZ0ZS
            dC9PNHRtVGJDUUtGY3hiODVLVUVwOGcK5jtco+BMNGyh+jMjxIWREg2WSHZ2irBK
            edVaooIz3+wu7PVGvrqy0ZVBttf7jxE6vh2GWC66PWBy74wbIRfGWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T07:19:03Z"
    mac: ENC[AES256_GCM,data:5yi3TAwPM+8AFTjFM78hSCdA+v8+Ee/MkBxG996V2zfHpl60hODSVZXc2RFYPqQsg562GGSE0f7ue/vWC2NmLSgyZB6JLVLOWf5nd9riPNcrSe7Oxa0asgPaUhTm5los/DRzmNhtqBWegWV/ECYrAQjHamua1DLhFJ0JgLrxlXo=,iv:yTQbwYHXDMo8q/IUvCMTRNMSkE4/6dk5NVrkmIYnOx8=,tag:M62ABJLzVLZLT5MsQw+EsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
