apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:u9X2pMs3dKeOeqxooFNIVZGYaTRl2/ROhila72SFc9Q/q9QLBanrmg==,iv:D384qKucUlCpdA/8LVaoxDiLGfAUSxFxKpSE2j/uCZA=,tag:8rXEMxJk0+g4lcqopfsihw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRUNZSDlIaWVhb0ZDdlhW
            elU0RDc0aWtJSTJWT0dOb2FNcGw0Q1dhUUNRCnYvTDF4UDJGSlVJNlZSQ004RWpN
            MVJUY3o0ejNWeGEyWVVNb0R1cFZ3WUkKLS0tIE9seVFraE0rU0ViSklyNkdMQTJ0
            bjE2TzN4Z1BFVXhDSm1NQ1B0dVprODgKW/l9LphXGiw2vdTHyKILYkWmyvRo06cI
            x8ncMJcvfzYo2bmiKN5E1yIamrVy9UZRMtOsvujuyOu65RxTgRLugQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T13:42:07Z"
    mac: ENC[AES256_GCM,data:2hSavT6xJFbQ/QnWGjowDHDDR1ZGpk7She1oG2NbEytUAD/q2BMmP0RWP1B6cmP2DZoELVqpQdS3vClV1e9beT6/P/549+rZR9eMgV74xH+0Fp/rmmqVpgy6gWwc9vTrfo51zrnWhXWG2AEXChfjgdRaBQ9ZXCFzfeKnzT8oEKU=,iv:/dS6SMZMgQR5qVJ+8sqjToFGwr4E+kPI+8m/8eLqzrs=,tag:sOb2KIcDDLB4UfCBaSQTNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
