apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:WO/EpUVB1fTMZIIM8oqXCbn3pIwwOH7h7fM9dmNisE4j7peWx98WSw==,iv:vUHRU6Uk3spEYgNDKMmPrRai7ssptrxlrC0AZ4JoeY8=,tag:fw1tg52oSLMvCyAA0NMGow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJenpUbU8rTDJVaE14VnFq
            ZVBKbUNUWCtLaWhJQ1BsOHo2OXgvSFdWNTFBCjI1Wk9CQXhsOVR3a3lTck45L1Uz
            RXcyL3FpRUlCellQYzJzZEc0UnZuclEKLS0tIFY2UzY0RmYvZ09kWUFpMndmdE9U
            WVJFcVE3TisxQnk3aFZqajZDUlpEWXMKoCburNBYO+Ok59wfHpnupOihMANC/DPY
            cFKMc7a6E81v00A2UYR7V7KDBGJiENxq7WzRjyyXwt5MqJWOkxIUjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T14:10:51Z"
    mac: ENC[AES256_GCM,data:SFq4XbzcPcdJjcxWjgLELSNkmUZP3eJFWIuG4pBqA7hTlvumcG6HJ2F5U6juvLOk71+QXqQmtKnI5ysCwQMS01G0hD62D9KWSRBnC764Wr02EFOemaN810gjunFW9yAlPqXhkvU1R/PGZpnTwGYTCLxFR9lorMZnUZ++pQXtUDY=,iv:hqtb1rUGxHdchpFHegVTI3eR/1P/SEWB/GMgS0GnXrA=,tag:8X5+JbaZ/SG0khyB86GdKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
