apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NJzSNE/FFPalKdFeyq71wanlCcOldDqhGINyE9nHAvkWKOAKCt86lA==,iv:zSttE7CpJVqpgeHrt7CX9jV/XoCqqa6wvVGsTpsiyLs=,tag:Oa0Pc/4vaRUVnByLcTXGGA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd1pOUFAwQzJrVURqYUcw
        U0NzR0N6ZU1PSks4ZldQSHFSbUpSTWtoMGpZCjFrN0dPOXMvb3RqeHZYeEtSc0t4
        bTlUNmtnQWRLZWFHV050eFZ6RURvbmMKLS0tIEdZc1dWYXJOL1pRSDlNUk83Y3Jk
        ekhpL3htRWtvZ0IyNlJDcy9HTHlQQ28KfviKa589zyKrMsTS8/le8aORbrQhOhNn
        muRx998hDGlxoS70WT/L8xbLzF9sGoyzaSdXr2vXQ0NM7exiYVRpgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:04Z"
  mac: ENC[AES256_GCM,data:S93fMbbXlbnw+RvtlHk/48fJ5RHM1iDRs2AWHAj7luN7UhC7k5R3H/O5gqISh+St31j6yYWbcefzkQWEs2CyCwjRMoNYlKlOsTBeOZfnPhERgKqtnCRKmSbgj5gyxMV9R0oFxSV8i5bMbuhCf2p7TZQbOdVdqDKJMeOn0vG4oQg=,iv:868IMnn/T55mFtLRd4EgiWjDXnuCtZSsGPzpd+ljfjs=,tag:riklOgev+zo4S8nUE/N3gw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
