---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deduparr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: deduparr
  dependsOn:
    - name: ceph-csi-rbd
      namespace: storage
  values:
    controllers:
      deduparr:
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: quay.io/kernald/deduparr
              tag: 1.1.0@sha256:2b2a695212bab92347f3adc07b334d96b00ea717bebe54134273cbdb5dd970ad
            args:
              - --config
              - /config/config.yaml
            env:
              DEDUPARR__PORT: &port 9090
            envFrom:
              - secretRef:
                  name: deduparr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/ready
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: deduparr
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: deduparr-config
      config-file:
        type: configMap
        name: deduparr-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
      add-ons:
        type: emptyDir
      tmp:
        type: emptyDir

    serviceMonitor:
      app:
        endpoints:
          - port: http
