---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-server
  namespace: &namespace services
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/services/immich/server"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: system
    - name: ceph-rbd
      namespace: ceph-csi
    - name: cloudnative-pg-cluster
      namespace: database
    - name: immich-valkey
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: photos
      VOLSYNC_CLAIM: immich-data
      VOLSYNC_CAPACITY: 100Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-ml
  namespace: &namespace services
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/services/immich/machine-learning"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: openebs
      namespace: openebs
    - name: immich-server
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-valkey
  namespace: &namespace services
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/services/immich/valkey"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false