---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: evcc
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: evcc
  values:
    controllers:
      evcc:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/evcc/evcc
              tag: 0.312.1@sha256:380cd375dff3159b65789f97218da09a168d0a355a164e31e9e2b278261b7a9a
            env:
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: evcc
        forceRename: evcc
        primary: true
        ports:
          http:
            port: 7070
      sync:
        controller: evcc
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "evcc-api.ds47.dev"
          lbipam.cilium.io/ips: "${LB_IP_EVCC_API}"
        ports:
          ocpp:
            port: 8887

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.ds47.dev"
        parentRefs:
          - name: kgateway-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: http

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /.evcc
      tmpfs:
        type: emptyDir
        advancedMounts:
          evcc:
            app:
              - path: /tmp
                subPath: tmp
