---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database.yaml
  - ./redis.yaml
  - ./init.yaml
  - ./deployment.yaml
  - ./pvc.yaml
  - ./http-svc.yaml
  - ./ssh-svc.yaml
  - ./secret.sops.yaml
  - ./http-route.yaml
