apiVersion: v1
kind: Secret
metadata:
    name: pgpool-secret
stringData:
    admin-password: ENC[AES256_GCM,data:DxtQqMEC5JsCB29yPPxiayADYKVAGOqH3ejaTYpsn3Sw5ws4,iv:NtHJSAW5GBARafDTflPhJ0M3fyNIFuka7N/lprpyxyU=,tag:jWwWd+qOTeLr82RP5a2aEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T10:54:38Z"
    mac: ENC[AES256_GCM,data:k0FCAw/jCfATMHhggS/YL6HZPCub0Hf3TSkh/1fMVjiR3sjd48zG4Sq24BXoI995/SMc1Bvu6AEF7KPtP4a3ibayGpAFfkQghXw68Yiz5vNzBZBo9gVBIKMKmmy/NW4SMKlQD5lN83YI1WcGXZUkShwM0RiCmJ+ATz9121XowpU=,iv:xWUMMub1qZkAcjKX/iKVirqY1CsuMJ9ppoCJhV10Q38=,tag:2DH4sBZ1SF4MS9A7GrMfAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
