apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
stringData:
    postgres-password: ENC[AES256_GCM,data:Fvhxcrhg9Q36B5olUa0gLMvJZsTzstPnrUzbBVItRE/+E0PT,iv:XTHtBUljyOqdqcvGkLw81jvAo3IWjIseDAOizhH1vVg=,tag:Y/DmQ1MEPFnxhW8OfhfQ+w==,type:str]
    repmgr-password: ENC[AES256_GCM,data:689CPoOf1e6ZC42PdS3tavNBUB2kuOUcin4bxDIkNBW3Hsqn,iv:JIJ9onokg3Dnl8u9YDMdFVoW7ozmrB9ybEJ4CpFI+54=,tag:j/CylcOzfAmvcP0McQ25RQ==,type:str]
    password: ENC[AES256_GCM,data:eoeCV6yGse/X9axNUp9Hc2BC0cgB9h1E124XNybaH/PIRXVL,iv:6p4TXF7xry2T3S/hIyBjEjyvt6v0F889Qpg1MeHl5bg=,tag:6F/ocujSaWj4Vn9JBAu+Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T11:32:22Z"
    mac: ENC[AES256_GCM,data:ojqu8qLVzygbuVTLPuBsxrqdta9vuyz8HXF6R+x25mY5A6vaoXMbmd76oAlQQJQHfdhg84+tUby0n/YjJducv0osUH/3sYu0qgku8ZifFscjRIz91xwigT/oBWPPYqzB2XkJHmi2bpdWn4IRO2OShJ9pkxBTuggHue6jX0z/eVw=,iv:AS0nUFsNVzhNoqgharuv6RYsGe77wD/m3I/bCjMX/KU=,tag:R2oq6aBhlSVG4Yj8X26VhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
