apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
stringData:
    postgresql-password: ENC[AES256_GCM,data:2azZgcBLzl+dlxEmNDAb8uJmC1qpaDiXpe0rzTYLGnvBG8eW,iv:FxqtRAkh8VIFv4mN9xci6XpUH8mlRhtoypxT7sogsXM=,tag:ct1lSceK9Wtjm/GUMDXPbQ==,type:str]
    repmgr-password: ENC[AES256_GCM,data:689CPoOf1e6ZC42PdS3tavNBUB2kuOUcin4bxDIkNBW3Hsqn,iv:JIJ9onokg3Dnl8u9YDMdFVoW7ozmrB9ybEJ4CpFI+54=,tag:j/CylcOzfAmvcP0McQ25RQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T10:53:32Z"
    mac: ENC[AES256_GCM,data:7Cf3htTurDV/y4z9Lrj5cPtbQWNVDNFhW3CeYc3Wwkg47ZI9CHUautswGrppm0S5x82IYGjexT5HrlWUgUv8u8S106UAAsiz9sUBieyy24IeKVTIL1wNokHq02UWmPpHtfWRv0YI5CJRgAXexg4/wSbky8DAhhWa2Fddja/yqHw=,iv:bQ4sOik913N7L8HJrUWpyOzWCOPr11u7XFh4VAzhqoM=,tag:/Ii0opTDi0rrJf5mJmiczQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
