---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: forgejo-db-secret
    template:
      type: Opaque
      data:
        FORGEJO__database__DB_TYPE: postgres
        FORGEJO__database__NAME: &dbName forgejo
        FORGEJO__database__HOST: &dbHost postgres16-rw.database.svc.cluster.local:5432
        FORGEJO__database__USER: &dbUser "{{ .FORGEJO_POSTGRES_USER }}"
        FORGEJO__database__PASSWD: &dbPass "{{ .FORGEJO_POSTGRES_PASS }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: cloudnative-pg