apiVersion: v1
kind: Secret
metadata:
    name: gitea-secret
stringData:
    username: ENC[AES256_GCM,data:Snkeqaus6w==,iv:dpt0R+5rNi2CXDbV75IZl197+m+xzimxJW/G+JH13L0=,tag:raugghr4Cs6oCai+EPrt2A==,type:str]
    password: ENC[AES256_GCM,data:qZg4R6NoGu9OLb8=,iv:IBEZvHcGz5d0Y2QT2ME8I8L/jZVzUZpQGe53y5AGfXA=,tag:K1xN6FSAwO8z0jwPUwlQyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T18:58:49Z"
    mac: ENC[AES256_GCM,data:Xqq/lO/v1qypJpEqVkA99QaIloQRIRxkFJKXqhlHk/d48UDGjKC8YZTfmSo/Bg3HPUmQSbOiehgH673qAA6EqFeA//MnzO6sfu+1nn01mYZCyPDFppNxDdEMXGQ0eyd8akzn64djoxu+CzNnyTf9FSmEjBdvXk50olDJtaeIyl8=,iv:5O+3ACRTpXEaJK4b3C41c6bBwluvcmwOOOl67b9QEMo=,tag:agWgcuXDT5yJ2p/hn9bcuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
stringData:
    postgres-password: ENC[AES256_GCM,data:F96cdPWxZzpE/OGPUQWjHGJMumXaSMUjsYKDH/ZyjDN+6gmB,iv:x5jrxEQmUm1fs57NKi37h44+lfV4CdGlM+zdVMYMQWM=,tag:MpJs4FIR+4vJX5IAdXNx6w==,type:str]
    repmgr-password: ENC[AES256_GCM,data:wCN6FKGVQX67cktGoR0CN2IB+Ue+wzuLXwiKkogZ0p1tAt4w,iv:XhunLsXOosQ2W1wZygyO1g5qXKy1w/Rpq5bR+iNEsak=,tag:j1508ihh11uQ85mt6uf/TQ==,type:str]
    password: ENC[AES256_GCM,data:BvsAtIDK+ozyw6kgN61kjvTfSIwHRXVvXIcDqpIPCQDLkvF6,iv:4TiZWWLlZKxUOgZMLbqP3oS2vXNRSaPZnnb0Hsew+Vs=,tag:mNPff9mmsZP4LFcFOSCMwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T18:58:49Z"
    mac: ENC[AES256_GCM,data:Xqq/lO/v1qypJpEqVkA99QaIloQRIRxkFJKXqhlHk/d48UDGjKC8YZTfmSo/Bg3HPUmQSbOiehgH673qAA6EqFeA//MnzO6sfu+1nn01mYZCyPDFppNxDdEMXGQ0eyd8akzn64djoxu+CzNnyTf9FSmEjBdvXk50olDJtaeIyl8=,iv:5O+3ACRTpXEaJK4b3C41c6bBwluvcmwOOOl67b9QEMo=,tag:agWgcuXDT5yJ2p/hn9bcuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: pgpool-secret
stringData:
    admin-password: ENC[AES256_GCM,data:ogVW+UnajLiBedAlzd7BdK6NNBsfwCCrnuQ5tdErJDJoMn4m,iv:CQW+xnFTCQnowCCncM3HjOYVStb5+0yAy9J4MtSyf4w=,tag:XTQwXTMJefJOxdXZvlgWvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T18:58:49Z"
    mac: ENC[AES256_GCM,data:Xqq/lO/v1qypJpEqVkA99QaIloQRIRxkFJKXqhlHk/d48UDGjKC8YZTfmSo/Bg3HPUmQSbOiehgH673qAA6EqFeA//MnzO6sfu+1nn01mYZCyPDFppNxDdEMXGQ0eyd8akzn64djoxu+CzNnyTf9FSmEjBdvXk50olDJtaeIyl8=,iv:5O+3ACRTpXEaJK4b3C41c6bBwluvcmwOOOl67b9QEMo=,tag:agWgcuXDT5yJ2p/hn9bcuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
