apiVersion: v1
kind: Secret
metadata:
    name: gitea-secret
stringData:
    username: ENC[AES256_GCM,data:Snkeqaus6w==,iv:dpt0R+5rNi2CXDbV75IZl197+m+xzimxJW/G+JH13L0=,tag:raugghr4Cs6oCai+EPrt2A==,type:str]
    password: ENC[AES256_GCM,data:qZg4R6NoGu9OLb8=,iv:IBEZvHcGz5d0Y2QT2ME8I8L/jZVzUZpQGe53y5AGfXA=,tag:K1xN6FSAwO8z0jwPUwlQyw==,type:str]
    postgres-password: ENC[AES256_GCM,data:F96cdPWxZzpE/OGPUQWjHGJMumXaSMUjsYKDH/ZyjDN+6gmB,iv:x5jrxEQmUm1fs57NKi37h44+lfV4CdGlM+zdVMYMQWM=,tag:MpJs4FIR+4vJX5IAdXNx6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T09:21:50Z"
    mac: ENC[AES256_GCM,data:ZIxseEiYYK1j9/HituQWm/P85MbZrzSgOUt8+zDXJzOECjgngSfnefijeCKvHKUu5kUWY9vfuhcoDAVkLGlTeuHSbkPUMYyeLzoBKSMeiHImXcq7aCJgDdUYUYrWdBRlSy/utdx6tU6cvHaniyrGDFSimH2lXTIH4jwCJjYv2U0=,iv:6NQKpiQwgC9AA56n8iYb5sufJL6wtEaMsIUvIGX/Rqk=,tag:Um2E586oVW8vQfokXPLpJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
