apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
spec:
  interval: 30m
  chart:
    spec:
      chart: newt
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: fossorial
        namespace: network
  valuesFrom:
    - kind: ConfigMap
      name: newt-values