global:
  image:
    tag: "1.8.1"
newtInstances:
  - name: main
    enabled: true
    auth:
      existingSecretName: newt-secret
      keys:
        endpointKey: PANGOLIN_ENDPOINT
        idKey: NEWT_SITE_ID
        secretKey: NEWT_SITE_SECRET