apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:nxkz2crNOAnjtUJROxHnSjXua2E9MGLNvNlEHSKKheY=,iv:By6ocic2cIQ1Wt5+YThIO9QvE+BXH+88SXDD3GdB8Hg=,tag:h7FQcgWwmS/z7RncVcqmBQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q2tvOGc0Wi9IUVNGcVZs
        NUZKM1ZxTTJSMDRKeUg1OVBVbEdzc0V4OEdRCjQrRTBRcHExM24vakIxb0NGQW9J
        cUh3ZTZuVUczdXFoWk9zSlA5SFlCa28KLS0tIEpacmNWZUFlY091LzRnYnpVRThj
        Y25LaG1tNC9wRlF5Uk5jaUVkUExrK0UK8d/vq1x0QcZ/ZpQB9uP11MhiMVVZt1wT
        Mn1pe5Dcw88l2K4giVz529VykNysgRJBUeJGK8XwSVmnihB7pHZApg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:05Z"
  mac: ENC[AES256_GCM,data:rQrveUlyEwf228nJaOu/VnyHAOsORU7xgX4IEftH0VqUxVy6jiic0E2AP3EEgd0+gtMhhRRCvEGLx8slL0ANoxxXSGr6z7TfHU6VCMi2HzsafLKRjJe8DSdBhdHg54twikJj87aY/KAPMmANyHGYBdxw4VP2KJzGNUH3XE/AOJ8=,iv:7KBSM360CtQ9URgof+s6tS9e/a1DruEb7h/K+2dsY0U=,tag:37D1aB+3yuiAQHSOd4qyhw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
