---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-technitium
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: external-dns-technitium-secret
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: "{{ .EXTERNAL_DNS_SECRET }}"
        EXTERNAL_DNS_RFC2136_ZONE: "{{ .EXTERNAL_DNS_CLUSTER_ZONE }}"
        EXTERNAL_DNS_RFC2136_HOST: "{{ .EXTERNAL_DNS_HOST }}"
  dataFrom:
    - extract:
        key: external-dns-technitium