---
apiVersion: batch/v1
kind: Job
metadata:
  name: coder-db-init
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
          envFrom:
            - secretRef:
                name: coder-db
            - secretRef:
                name: coder-initdb
      restartPolicy: OnFailure
