---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    volsync.backube/privileged-movers: "true"
  name: home-automation
  labels:
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
