---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app windmill-mcp
  namespace: ai
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: windmill
      namespace: ai
    - name: toolhive-operator-crds
    - name: toolhive-operator
    - name: toolhive-config
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/ai/mcp-servers/windmill
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
