---
# yaml-language-server: $schema=https://schemas.tholinka.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 'ds47-dev-unifi'
spec:
  secretName: 'ds47-dev-unifi'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'controller.ds47.dev'
  dnsNames:
    - 'controller.ds47.dev'
  keystores:
    jks:
      create: true
      alias: unifi
      password: aircontrolenterprise
