---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: ceph-csi-rbd
      namespace: storage
  values:
    controllers:
      unifi:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/jacobalberty/unifi-docker
              tag: v9.4.19@sha256:ef032346e2ebdcadaadeb27e38be55f97e6b5ed6cea333d5d82ae9b58ae4068b
              pullPolicy: IfNotPresent
            env:
              RUNAS_UID0: "false"
              UNIFI_UID: "1000"
              UNIFI_GID: "1000"
              UNIFI_STDOUT: "true"
              JVM_INIT_HEAP_SIZE:
              JVM_MAX_HEAP_SIZE: 1024M
            resources:
              requests:
                memory: 1Gi
                cpu: 50m
              limits:
                memory: 1250Mi

    service:
      app:
        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: 10.100.90.81
        ports:
          https:
            port: &port 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    persistence:
      config:
        enabled: true
        existingClaim: unifi-data
        globalMounts:
          - path: /unifi
      cert:
        type: secret
        name: 'schwarz47-at-unifi'
        advancedMounts:
          unifi:
            app:
              - path: /unifi/cert/cert.pem
                subPath: tls.crt
                readOnly: true
              - path: /unifi/cert/privkey.pem
                subPath: tls.key
                readOnly: true
              - path: /unifi/data/keystore
                subPath: keystore.jks
                readOnly: false

    route:
      app:
        hostnames:
          - controller.apps.schwarz47.at
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
            timeouts:
              request: 0s # websocket, never time out
              backendRequest: 0s # websocket, never time out