---
# yaml-language-server: $schema=https://schemas.tholinka.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: lets-encrypt-unifi
spec:
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-secret-store
  selector:
    secret:
      name: schwarz47-at-unifi
  template:
    engineVersion: v2
    data:
      # needs to be b64enc
      keystore.jks: '{{ index . "keystore.jks" | b64enc }}'
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        remoteRef:
          remoteKey: lets-encrypt-unifi
