---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      data:
        N8N_ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: n8n
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: n8n-db
    creationPolicy: Owner
    template:
      data:
        DB_POSTGRESDB_HOST: &dbHost pg18vec-rw.database.svc.cluster.local
        DB_POSTGRESDB_PORT: "5432"
        DB_POSTGRESDB_DATABASE: &dbName n8n
        DB_POSTGRESDB_USER: &dbUser n8n
        DB_POSTGRESDB_PASSWORD: &dbPass "{{ .DB_PASSWORD }}"
        # --
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: n8n-initdb
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vec
        property: password
