---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./pocket-id-operator/ks.yaml
  - ./pocket-id-instance/ks.yaml
  - ./namespace.yaml
components:
  - ../../components/common
