---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./namespace.yaml
  - ./litellm/ks.yaml
  - ./n8n/ks.yaml
  - ./ollama/ks.yaml
components:
  - ../../components/common
  - ../../components/volsync-ns
transformers:
  - ./transformers
