---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-blobs
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-generated
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block