---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: influxdb-secret
    template:
      engineVersion: v2
      data:
        INFLUXDB_USERNAME: "{{ .USERNAME }}"
        INFLUXDB_PASSWORD: "{{ .PASSWORD }}"
        INFLUXDB_TOKEN: "{{ .TOKEN }}"
  dataFrom:
    - extract:
        key: influxdb