---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evcc-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  data:
    - secretKey: SPONSOR_TOKEN
      remoteRef:
        key: evcc
        property: SPONSOR_TOKEN
    - secretKey: SKODA_USERNAME
      remoteRef:
        key: evcc
        property: SKODA_USERNAME
    - secretKey: SKODA_PASSWORD
      remoteRef:
        key: evcc
        property: SKODA_PASSWORD
  target:
    name: evcc-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        evcc.yaml: |-
          network:
            schema: http
            host: evcc.apps.schwarz47.at
            port: 7070

          # unique installation id
          plant: 06bb734198c26102ea34e72cbf0f2926c060ce2551ec1b71107795d0fb4e1466

          interval: 30s

          sponsortoken: {{.SPONSOR_TOKEN}}

          telemetry: false

          meters:
          - type: template
            template: solaredge-inverter
            id: 1
            host: 10.10.20.145
            port: 1502
            usage: grid
            modbus: tcpip
            name: grid
          - type: template
            template: solaredge-inverter
            id: 1
            host: 10.10.20.145
            port: 1502
            usage: pv
            modbus: tcpip
            name: pv

          chargers:
          - type: template
            template: keba-modbus
            id: 255
            host: 10.10.20.148
            port: 502
            modbus: tcpip
            name: wallbox4

          vehicles:
          - type: template
            template: enyaq
            user: {{.SKODA_USERNAME}}
            password: {{.SKODA_PASSWORD}}
            capacity: 25.7
            timeout: 10s
            name: superb

          loadpoints:
          - title: Garage
            charger: wallbox4
            vehicle: superb
            mode: minpv

          site:
            title: HaMaVil
            meters:
              grid: grid
              pv:
              - pv

          log: info
          levels:
            site: debug
            lp-1: debug
            lp-2: debug
            cache: error
            db: error