apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      sonarr:
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 5000
            runAsNonRoot: true
            fsGroup: 5000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.12.2866@sha256:8690925866b385cbce810ae83151b0151fc3fe3579c21cd8410f081ff140c798
            env:
              TZ: Europe/Vienna
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__APP__THEME: dark
              SONARR__SERVER__PORT: &port 8989
              SONARR__AUTH__METHOD: External
              SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
              SONARR__LOG__LEVEL: info
              SONARR__UPDATE__BRANCH: develop
            envFrom:
              - secretRef:
                  name: sonarr-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 20m
                memory: 256Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: sonarr
        ports:
          http:
            port: *port

    route:
      app:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: network
        hostnames:
          - sonarr.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: app
                port: *port

    persistence:
      config:
        existingClaim: sonarr-config
      add-ons:
        type: emptyDir
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 10.10.200.50
        path: /mnt/storage/media
        globalMounts:
          - path: /data/media
