apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    api-key: ENC[AES256_GCM,data:gXv5Y9SvY7/jUfdlP1eh/KI5cphOGSVx/Yp3IcOJAcU=,iv:Pc49YX+92K/mCilcMbV13YgJiV6Ft6v3MfT2nBSOUOQ=,tag:rhgGFLc5lY+6HNifq0yH5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqclYwYTNZTnBxVDNhRkYy
            T29rYmtVeXpiS2E4R20zWndYdlhRQVVZTGwwCkxiSzZuYXY2M3IraXRMMlk5ektJ
            QXh3SUVmcWV0VmdMcWtVaXRMdFRlcVUKLS0tIHBiSGhMTmRwRHo4U1RaYjROREZz
            eldVbFFyaEFnY3ZUa2VjMkcvOXoxQTQKBy+aCtqs4EkANos9TbqRgTTr5w1m8cXz
            +Pot8g6P18WbbNwZOkvSxmSkMDQGYL9ZeV3SmUHmtliXZnuJ/zYc8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T19:18:52Z"
    mac: ENC[AES256_GCM,data:TlzaXyvmwvmat/MGTtUCZcx9fA4RFoYw8vJH62t3QmZ0IxnY9riGU3L0s78LuWkMW9o14yURwcnr7/3NezOHVxMbe82ttbh31B1PIsUSU1xfobF8mdDraswueTY/F0/nqJtUmnepqb4DT9yztkLHoQ5f1PFinCojGA1YzTCS7AM=,iv:J/y2xbDi/eFbdlQiDbvHibu0U83kphT0YA8mItWbjcw=,tag:Az/WyEn6cFzEy8O86FyEHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
