apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  api-key: ENC[AES256_GCM,data:Ti3o+wt6U+XtQtx0qbQ2A2OHVwzaqdUeCrClTHcvsu0=,iv:9vLNT1gdmuWeBqAM9QZ3nib6a5e4+PfBF6swwn5I4Vc=,tag:zoo1KvkCPjEGjeXSHSMf3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcTRkNlZRb0tBUVFXNnFH
        UjE3ZXBCRzArSThxRm5uNEM0QSs1MzB6d1ZJClAvczdkbkZSOVEyVGxpc1JhUm5H
        TGdLcXVCVm5YdFZNM1NBMmJVTjQ2R28KLS0tIHJLbkhsdTdlb3VJLyt0cmJtOEtt
        Z0xOSXc4dmsyeGVMYUdtUFhvaldsQkEKMXvozgPqdZTKUZV2lUcVHV35EZwDU0G2
        4cAulIAB3GEyi40R6M2y/25dJmddV/mmA8SbZ9cmTrG1B9wT0NQ0Gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:06Z"
  mac: ENC[AES256_GCM,data:IJEn9HyPnuMTvoLgHy0cDiSIwUMDQZUaIgVklcUZyS2q77vLOf7Gfk3J1UROnbJvuHinfuHBkqNvR+fdCPUaYDmA7kZYwQWUnLK5Yh4lXC5wGc7GjfObiV8OtbIuI9tCQEmUv2rl5vdEp9JmcT37LeasGs7dL2avSfJFJlYPhJk=,iv:j7UIW3SVYNDOoeHOl8eUNlf4xGH6c85MTruomj1M1xY=,tag:9QB3+oGxFjpRWjv1LJIBdA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
