---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-adhome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: external-dns-adhome-secrets
    template:
      engineVersion: v2
      data:
        URL: "{{ .URL }}"
        USER: "{{ .USER }}"
        PASS: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: adguard