---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-adhome
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/zekker6/external-dns-provider-adguard
          tag: v1.0.0@sha256:20f2fb1d2f9da1a3c704f06982fb00ec80a758affee1c9cb52a3f89130422795
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_HOME_USER
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-adhome-secrets
                key: USER
          - name: ADGUARD_HOME_PASS
            valueFrom:
              secretKeyRef:
                name: *secret
                key: PASS
          - name: ADGUARD_HOME_URL
            valueFrom:
              secretKeyRef:
                name: *secret
                key: URL
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    policy: sync
    sources:
      - gateway-httproute
      - gateway-tlsroute
      - gateway-tcproute
      - gateway-udproute
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: k8s.
    domainFilters:
      - schwarz47.at
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret