apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
stringData:
    api-key: ENC[AES256_GCM,data:Jxr4X0opQDAzFDyUQCbb4FWNKPSWgjiOXd+Vb8R5ovs=,iv:QWqcbCYHTkkJg4zfNpAgYVrVg93mQaC3YwJKmbp2fdU=,tag:+kBireifyaNJ0i5DviHm/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqclYwYTNZTnBxVDNhRkYy
            T29rYmtVeXpiS2E4R20zWndYdlhRQVVZTGwwCkxiSzZuYXY2M3IraXRMMlk5ektJ
            QXh3SUVmcWV0VmdMcWtVaXRMdFRlcVUKLS0tIHBiSGhMTmRwRHo4U1RaYjROREZz
            eldVbFFyaEFnY3ZUa2VjMkcvOXoxQTQKBy+aCtqs4EkANos9TbqRgTTr5w1m8cXz
            +Pot8g6P18WbbNwZOkvSxmSkMDQGYL9ZeV3SmUHmtliXZnuJ/zYc8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T14:17:34Z"
    mac: ENC[AES256_GCM,data:5dvgkT9p62DhJFwsyy1CDNwuam1o0hg51hpYv4lttkVUqqKmXjoeBMabFqH9CyWq05B2nL3QgK/KyyIBV585HjdMCda9L3D2x8iPS1ZUKMJjfioWKJaINFG4m463Kl82bDhlzDv2YsTlPF0Ut9bwPMT0M+LLSL5hsV78vBiZ/Sk=,iv:E+inFHIRkYJC1ia3DSX4nbE6wRU9ikPvppCV+miPSWI=,tag:zr84TVoDxy1qFk4uxy+L4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
