---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: pg18vec
  name: pg18vec-podmonitor
spec:
  podMetricsEndpoints:
  - metricRelabelings:
    - action: replace
      sourceLabels:
      - cluster
      targetLabel: cnpg_cluster
    - action: labeldrop
      regex: cluster
    port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: pg18vec
      cnpg.io/podRole: instance
