---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-maintenance
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: volsync-maintenance-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        KOPIA_S3_ENDPOINT: "versity.ds47.dev"
        KOPIA_S3_BUCKET: "{{ .KOPIA_BUCKET }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_REPOSITORY: "s3://{{ .KOPIA_BUCKET }}/volsync"
  dataFrom:
    - extract:
        key: s3-versity
    - extract:
        key: kopia
