# Rename to unsealer-secret.sops.yaml, fill in the keys, then:
# sops -e -i kubernetes/apps/vault/vault/app/unsealer-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
stringData:
  VAULT_UNSEAL_KEYS: ENC[AES256_GCM,data:eznnZlUFCCKDLhVoxZ8fhgHw9qBbBSJOqgqKL35s/z4tC8zZKGGcC1DERkTboosvwgu7JKsntOSjfKqHy47PT2dhUl1M6XdDNR5ncx0wb3ukXiDlsMvRzImYBxxjpPQtfE+pYtiFdZn9M6nCZEd0o6p0+IFLo5kL7TQ7SU2u3yg+LbMgcuU=,iv:UKMG/sYosz55n215+mv6eRSvgvmUAm0RYAb9t6B7G+E=,tag:kgl1aoqOMV1lny/PpFzr8g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUnpsZldydXU2azc3OXda
        Y2llSW1uT1N2UTNLQkhKdlFyRGtvVGFOZzFRCkltK3pCTDErTVkrMHZYZlRINlVQ
        MnpzQkRPVGJMODVtNzZTdTZWVG9ycUUKLS0tIEtPUnVaMU1qZTRIMHA5VHVnOEti
        MmJHbW5UVFFOSU5TZkFLZWZ4d3RlU0UKMhliWRPqIu8zByp4pG9E2Syz5fnp6Hav
        MXRrv8IGzARnGmXY0qbUepvR5Ub1Y+DXMd6NnV6vHe0Rwachy1XwJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1drlg4urwuhv9n8wgyhjwau7agpxq30n7wsdyhh6u5w9nk6e9p3jsdsqvtm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-29T09:20:35Z"
  mac: ENC[AES256_GCM,data:QowmQEhIkLt5PYuCHUG81UO4oazuo8qcyE9ftXENDJtOgLZKsBTORfxMlwIjO1B4wftjD/BxcouotIF3jZFkI+WJXVRCvmi9pA0AQze3u1f71iT7tA1BbKLQvj1ItpMmt+LPo6oU9p401UVgyY2yaS6eMHTwNQiz4kVigb8U2LE=,iv:4At66Pd6/UwTashCy8jeQFo48F9P7BQ33X8fPCnlpKE=,tag:rAGFHIgkr5d7nlP5oSygdg==,type:str]
  version: 3.13.1
