apiVersion: v1
kind: Secret
metadata:
    name: vault-unseal-keys
    namespace: vault
stringData:
    VAULT_UNSEAL_KEYS: ENC[AES256_GCM,data:jUSoh9je74g/Oh8s1b/hKRW8YHX4SW7MxZSMJ1u0zv6VPiHmYj84s/6KGM7FsWrp5MbNFBXeAvquY5mELgoznC0u/8gfcgUqMe80Uigq79kZ7sDVF/2EX2qBuVE11wzpYYn/o8LjGT16Ql5P9NneIPaj/gtXkfAR1y5RuHOMYLsd+LPXQW8=,iv:ln9598yxAvnoWNX8ZR+ikIapqdPS8XhY3qxNGrvAxSo=,tag:1MQR/8SvzLgxWFFOF11lOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eGFydmt0MXpZb0xuRlZx
            T05GemZ0bml1Mk9qTGJQL29OMHV0RjYyV1UwCk1mQncwaVdnZy80TWlTUG1WS0Zq
            aVNIUTN3dkk2ODJZVDNXL3ltRGNmV2MKLS0tIHVFVTEzM0ovTGxKenc2VWNKMTA2
            TmVUVHRCdHpDVzdYYlRMR3VwMU4zemsKUufuDyuNXxo7tI6QAnwXFNYqdzWDr1dO
            vEneQNl4nWQrDr3TIlJ2yY0pnYKIdOCu9ZTTkw+AssmuVbamM67oHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1drlg4urwuhv9n8wgyhjwau7agpxq30n7wsdyhh6u5w9nk6e9p3jsdsqvtm
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-29T08:14:53Z"
    mac: ENC[AES256_GCM,data:uN+RDhbFFm9xZ94gOb90gHo8+IgmVRUGnc7FyCR8gdy9mtOLaIubdNxNze6JM9NrH9i4Rnurp1MvKFpfOBdqhMd9KheUFT5XMEM4qf+gBUlY8DlNJ4IpH+7CNW6SIP9FTk7PkE3yVp0znwT/f/p7O1oHMWVgZAtD4uoTIPYhvxg=,iv:byE8USYpmclnjvXlQsEO5iIqHK99WtyTCV+lDXyOtOw=,tag:N+/YZLCE9VF+U7hD4kk/Ug==,type:str]
    version: 3.13.1
