apiVersion: v1
kind: Secret
metadata:
  name: vault-unseal-keys
  namespace: vault
stringData:
  VAULT_UNSEAL_KEY_1: ENC[AES256_GCM,data:kdXINnLcmNLqCRPvMSqCZV3bC20GQXB0Ccz1aIZElZxygRMLxrtlWcBdIN4=,iv:4Rf44L4I71CsEl2LbaoSMlWwpCHThVRPYXDpkkU8AcE=,tag:bKJzR0ufBiFZeQxteRp+VQ==,type:str]
  VAULT_UNSEAL_KEY_2: ENC[AES256_GCM,data:FxudBItXRPdeljDJJMbjRWOcLVFq7MceWLsEFWAzzXWFJffGXbH+ZhLkFSM=,iv:J+3eoGRKltekx1n3o1trIYt1f2futjcLGVRjHSFWBk8=,tag:8rt7h6DLVSGr0Xd0ISzOeg==,type:str]
  VAULT_UNSEAL_KEY_3: ENC[AES256_GCM,data:nhnaG8/uUWUOwDRgsJFJumBnTGsa8IlAGUjznwWvz/YS2dgbVST+5n3bOto=,iv:w0IZgWoid/9Yn3JH6loBuVxg1ZJlkh5NaYBtWT7IDIA=,tag:0fTeEr9WmQrbyuVlL4wgFQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQnpJMWo4aDhiejRPL3NR
        OE1jblYrd2pUV1huY013NFNNSi8ramVleVdvCkpjNXo1NC9ORjFoNEs1bTlodmJs
        ZFc2dkZnRjdsbVpWYUV0b3NFRzAzNTQKLS0tIGJ3cjdwM3FFV3Fib1BHT2JGK2dl
        b0ZxK0tNWCtmWm1WN3MvRXpJUm1rNDgK4RfewEMoDdDZahal5xipEU5FsUm3p9jA
        0Rdx/NV2sp2G6by9vfibxyKt4h/Dy55LNhCfZtLmPYDWPASOPl7Q4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1drlg4urwuhv9n8wgyhjwau7agpxq30n7wsdyhh6u5w9nk6e9p3jsdsqvtm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-29T07:39:01Z"
  mac: ENC[AES256_GCM,data:+HcZIvTIom4M4mM+mzrulNhfLYFjDRmKxsQvHclbfH0YaxBe9NI9K7sn0dghnrNezo8hgZmtoukV8+YtbkXfxmFwjQhftWkF3RbarHy5LBiUm8s5eTk8g5PX5uQl52XNsWg6sUbdjVQh1IqARUaAr1zKC5HxkWvNBK2HwM1Jwyo=,iv:AaIDMAqWEtd5C7TZzsH+xTlsDJV2ADQLCjeRNQHttGQ=,tag:zQvc96z9ZdXXgS9eaGhXNw==,type:str]
  version: 3.13.1
