# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      renovate:
        annotations:
          secret.reloader.stakater.com/reload: renovate-secret

        containers:
          app:
            image:
              repository: ghcr.io/renovatebot/renovate
              tag: 40.40.1@sha256:ef85bf681b6a94e1a2a8afdcdeff8caa2fb92d7926538657671e8118ea03dffd
              pullPolicy: IfNotPresent
            env:
              LOG_LEVEL: debug
              RENOVATE_PAGINATE_ALL: "true"
              RENOVATE_CONFIG_FILE: /usr/src/app/config.js
              RENOVATE_CRON: "0 3 * * *"
              RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@schwarz47.at>"
            envFrom:
              - secretRef:
                  name: renovate-secret
            probes:
              liveness: &probe
                type: HTTP
                path: /health
              readiness: *probe
              startup: *probe
            resources:
              requests:
                cpu: 250m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 4Gi

    persistence:
      config:
        enabled: true
        type: configMap
        name: renovate-config
        globalMounts:
          - path: /usr/src/app/config.js
            subPath: config.js
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp/renovate

    configMaps:
      config:
        enabled: true
        data:
          # language=javascript
          config.js: |
            module.exports = {
              "platform": "gitea",
              "endpoint": "https://git.schwarz47.at/api/v1",
              "token": process.env.FORGEJO_API_TOKEN,
              "autodiscover": true,
              "cacheHardTtlMinutes": 240,
              "onboardingConfigFileName": "renovate.json5",
              "onboardingConfig": {
                "$schema": "https://docs.renovatebot.com/renovate-schema.json",
                "extends": ["config:recommended"]
              },
              "detectHostRulesFromEnv": true,
              "onboardingRebaseCheckbox": true,
            };