# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.6.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    controllers:
      renovate:
        annotations:
          secret.reloader.stakater.com/reload: renovate-secret

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: renovate-secret

        containers:
          app:
            image:
              repository: ghcr.io/renovatebot/renovate
              tag: 39.187.0-full@sha256:fd098a786c1813e3b3e92f895eb9900069518e120b98c994c23715fe29087080
              pullPolicy: IfNotPresent
            env:
              LOG_LEVEL: debug
              RENOVATE_PAGINATE_ALL: "true"
              RENOVATE_CONFIG_FILE: /usr/src/app/config.js
              RENOVATE_CRON: "0 3 * * *"
              RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate@schwarz47.at>"
            envFrom:
              - secretRef:
                  name: renovate-secret
            probes:
              liveness: &probe
                type: HTTP
                path: /health
              readiness: *probe
              startup: *probe
            resources:
              requests:
                cpu: 250m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 4Gi

    service:
      renovate:
        controller: renovate
        ports:
          http:
            port: &port 8080

    route:
      app:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: network
        hostnames:
          - git.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: app
                port: *port

    persistence:
      config:
        enabled: true
        type: configMap
        name: renovate-config
        globalMounts:
          - path: /usr/src/app/config.js
            subPath: config.js
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp/renovate

    configMaps:
      config:
        enabled: true
        data:
          # language=javascript
          config.js: |
            module.exports = {
              "platform": "gitea",
              "endpoint": "https://git.schwarz47.at/api/v1",
              "token": process.env.FORGEJO_API_TOKEN,
              "autodiscover": true,
              "cacheHardTtlMinutes": 240,
              "onboardingConfigFileName": "renovate.json5",
              "onboardingConfig": {
                "$schema": "https://docs.renovatebot.com/renovate-schema.json",
                "extends": ["config:recommended"]
              },
              "detectHostRulesFromEnv": true,
              "onboardingRebaseCheckbox": true,
            };