---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceph-csi
resources:
  - ./ceph-csi/ks.yaml
components:
  - ../../components/namespace
patches:
  - patch: |
      - op: add
        path: /metadata/name
        value: ceph-csi
    target:
      kind: Namespace