---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-signal-db
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: matrix-signal-db
    creationPolicy: Owner
    template:
      data:
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        # --
        INIT_POSTGRES_DBNAME: matrix_signal
        INIT_POSTGRES_HOST: pg18vec-rw.database.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_USER: matrix_signal
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-signal-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: matrix-signal-initdb
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vec
        property: password
