---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    database: allow
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: monitoring
spec:
  hard:
    requests.ephemeral-storage: "500Mi"
    limits.ephemeral-storage: "4Gi"