---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocis
  namespace: services
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: ocis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # WEB_OIDC_METADATA_URL: "{{ .ISSUER_URL }}"
        # WEB_OIDC_CLIENT_ID: "{{ .CLIENT_ID }}"
        # OCIS_OIDC_ISSUER: "{{ .ISSUER_HOST }}"
        OCIS_JWT_SECRET: "{{ .JWT_SECRET }}"
        OCIS_SERVICE_ACCOUNT_ID: "{{ .SERVICE_ACCOUNT_ID }}"
        OCIS_SERVICE_ACCOUNT_SECRET: "{{ .SERVICE_ACCOUNT_SECRET }}"
  dataFrom:
    - extract:
        key: ocis
    - extract:
        key: sso