---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-mcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: homeassistant-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: mcps/homeassistant-mcp
        property: HOMEASSISTANT_TOKEN
