apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mw28r3CDIRAwBKEH,iv:EDvco5uukbgrr+6BGPKysuM78AUcnivm2hs7XEWvutk=,tag:9ksthsLSdKL/g4qcwnJxtA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:lppKCtZorhFk1sNC5vx/Xywh5Pk=,iv:nmWpmM053nKemVntwytcqnM6aWaa87tJROCAZ7INrY8=,tag:FAolt2XpeYSjbb2BByepbg==,type:str]
    SECRET_EXAMPLE: ENC[AES256_GCM,data:kUpymEzaUCsjlVtetmelYgKS8DA4eJ1k3bSaRnxbzVwb/74Bv31ed0gp6wMfXHEUn17dihDsdJC2ZgQzP35b+fTPDOBq3B2KcI9q5hFu0L2D,iv:TWGQY+A1RLYxTtMtWIVoK7lIrxAJE1V7VbMLB+DgBkY=,tag:K8ihxUVlYXxy7o/9Wdpe9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRHhFYkVySkkrc3ltVW9x
            MFBNZWdkaGw3STAydWk0RzRBTmQ0NHhaTjNBCkI3NDVXb0I1MkZjcTc4TkZCam1T
            N0dSYmdZVHAzeFJ2S2ZpL245UmhtMlUKLS0tIDNwaFhHWXRNNS8zZS83ME9xa1VO
            ZkZJQ204bnV1ejNoR0ZvVThaNEhkWnMKXyqeLioKCyzgLPRDiy8TyHtWk56YsDUY
            vwY5zQAiSeypIZ6sAFnn2G+DUw/F6J4uJ0m1Ta/BAcIt/ITmobuD9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T09:54:35Z"
    mac: ENC[AES256_GCM,data:fCipbV7rOjEdik+K8z21vllteQhrFo3y4PUIBejFmb34NuujEJqBGHPYSG8kTuVJWfKGVPUYyWjuUFLiGaBP+OcHpXKVWebqFSQ1PoThUGfMCj+uqleHwu3/7vgi7T6yNVP3l9PVEgnV2jGvagG9Z+CkKjnwuXOz8PMgPcdMcjc=,iv:dx0sQweoLG6sBgHy3I/1wUK36m/L4wWTM7wIQK7epnM=,tag:WzrcZiNFAFe3bSnQCn1UAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
