apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:3noGark9Agl9GUnO,iv:xihvR3ZIS71lIE9vj6YsglXCf6aVeHNaEF5syD8V5Yk=,tag:i0eD4wDEtgWT5X8gTWdJEw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FAo6UzrbDXotqS1VR0FutjlC4YY=,iv:5dlUS5N2fG5opXzUdBjgOK1Wkt2ika6pOTZO0RVLL/A=,tag:I7n600XwKeA86BnZnTR5tw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wGf4agsF/CwYPlaz64VFlIA/ZWU8r/51mpPK7v1OGx7Jjhr4,iv:tvZqkjoV9ssnRHVQ+2GnKEEw6V3STd3LSarQ3zIKFJQ=,tag:0+qRCOp/cK52uWnjaE0Egg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10rnp5c6u2cgdp8zm5cjg33nux8fql2epjumzxqe7gw5lpsnx9djsh6qxy2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV0JkenQwUkwxOEVGWjcr
            WkExTzFzV1M2YVB0VnRaSHgxZTZ4RTRZZ2tnCjl4UlFCWkpRaWhaSWJObFFzZ2py
            RmR3c3Fvaklkc25kK1BibVd4UTgxeHMKLS0tIDQ4NDZ2L1hnQWxxeVMwdmRBS0JQ
            NWE3S3AySmNVWGZLMVpRZXVzc1RuTTAK/vowGVgSEmTO3rvzgkzgRVsj4Kd/JDLG
            3ZDsWJM/qlZJ3Fete1FYfJ2XIDqskmzsvrNZBuVG82mNY1LtR9rgmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T07:19:04Z"
    mac: ENC[AES256_GCM,data:AmJMSx9YzHOsTiytP3SGYAD/uptmYwDqsFwSWD2vAUFGAlLfPEMW4ZZaCBNzxeGcdRA951xw2VIMJJSqd2+dGfNhWjeAMqqum7ri3/hw3/HKC+CMgykeM0ENuuqU6XsNWyFM9ZFLk0aM/4icV9kDdu0pgnw3d9WPqAwfwOWdOMg=,iv:a+Qws07Lwu1Z9VlVyTX7ydymORCpraGnCfYx7o2RPj8=,tag:1K5CwzLq24jx11Qy76s4Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
