apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:j+H6DJlwUSG2e1zi,iv:izjWeNXDp0HgbxphzVCQraf+uSjrhX6JR6EYxqBRN6A=,tag:eMxWY4jMUYi68xeRWV+URQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NNGQePZMhaQlYMwzhfoWbbKJGxU=,iv:B5l4kmjPwOeNJO5RVMPMLD1xxVOOu5/vqHIin48nCkY=,tag:IFsgmL8rBTdqPdr/fiBMSQ==,type:str]
    SECRET_EXAMPLE: ENC[AES256_GCM,data:jsDk3JQgNTptNGPfinhoTfBoV07XsFuIapqcUPxoK4mRe8HMSkZeaPpt/q35DdFrJskzwPVuCSLeNUl6NtMe2BCAdCA7XMwFxlKdRfACl6/1,iv:wRBH907znilcRrSNf//fsatVYL33Gmf6/w52jr8aNns=,tag:4EZWd+1vgb89e4ja2xTkHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN0Q2bTRrZERJL09aMkU3
            eVF4cTRLWm8xYm5lakY5V0VOUlNBazMzckdZCjViVnpjcm5MVm5LbEpsQ3BQS1d4
            QytjKzhmaWN2N09FVGRmUDRRbkRoT1kKLS0tIGdGb2k2RW9IenlrOEpkYTB0cVU5
            VHZyMi8ydmE4Z2FvR1ZuWjFIRTRGZjAK6Hz32yuCIp8mIvwh61Fq2uAnBjvU+vLq
            qRt74zus65NbESAmqrD1KsQgiTufpoH1gHnM7bY9SWgwPcGUTrxn0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T09:05:20Z"
    mac: ENC[AES256_GCM,data:aJhZySmbmETu75wkUP/rmPOl4tmkG8sAUXMiu/f5k9rKE+cj4YaTsD09/syBqAWmGL5WiAaSt47uBnYWyzxCfL61rIeskpplIgS0KQcKWw7UlgShn5biEXecjMmxf+f1vr0k7iKPa0clZEfS3qHm0matv3v4BNyqxR4JLDfr1jo=,iv:BOG9OusIrQRXqRPIUkv8uFjs32B9AOpVCqlBq5XB2Xg=,tag:gDso//vwi4UsSKAdb9HEiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
