---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: emqx-secret
    creationPolicy: Owner
    template:
      data:
        EMQX_DASHBOARD__DEFAULT_USERNAME: "{{ .ADMIN_USERNAME }}"
        EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: emqx
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-init-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: emqx-init-user-secret
    creationPolicy: Owner
    template:
      data:
        init_users: |
          [
            {"user_id": "{{ .MQTT_USERNAME }}", "password": "{{ .MQTT_PASSWORD }}", "is_superuser": true}
          ]
        init-acl: |
          {allow, {user, "{{ .MQTT_USERNAME }}"}, all, ["#"]}.
  dataFrom:
    - extract:
        key: emqx