---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-technitium
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: externaldns-technitium-secret
    template:
      engineVersion: v2
      data:
        rfc2136-tsig-secret: "{{ .EXTERNAL_DNS_SECRET }}"
        rfc2136-zone: "{{ .EXTERNAL_DNS_CLUSTER_ZONE }}"
        rfc2136-host: "{{ .EXTERNAL_DNS_HOST }}"
        domain-filter: "{{ .EXTERNAL_DNS_CLUSTER_ZONE }}"
  dataFrom:
    - extract:
        key: externaldns-technitium