apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisparr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      whisparr:
        pod:
          securityContext:
            runAsUser: 3000
            runAsGroup: 5000
            runAsNonRoot: true
            fsGroup: 5000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: git.schwarz47.at/dominik/whisparr-nightly
              tag: 2.0.0.548@sha256:81037ce7d9dfe2180946423e45ee5f6fe43ae542905d50bd5c3581705a202100
            env:
              WHISPARR__APP__INSTANCENAME: Whisparr
              WHISPARR__APP__THEME: dark
              WHISPARR__SERVER__PORT: &port 6969
              WHISPARR__AUTH__METHOD: External
              WHISPARR__AUTH__REQUIRED: DisabledForLocalAddresses
              WHISPARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: whisparr-secret
                    key: api-key
              WHISPARR__LOG__LEVEL: info
              WHISPARR__UPDATE__BRANCH: develop
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                cpu: 1000m
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: whisparr
        ports:
          http:
            port: *port

    route:
      app:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: network
        hostnames:
          - whisparr.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: app
                port: *port

    persistence:
      config:
        existingClaim: whisparr-config
      add-ons:
        type: emptyDir
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 10.10.200.50
        path: /mnt/storage/media
        globalMounts:
          - path: /data/media
