apiVersion: v1
kind: Secret
metadata:
  name: whisparr-secret
stringData:
  api-key: ENC[AES256_GCM,data:WX9NVKnXdKU3e227S3Z3TKUIIR0bvu2CDzxP8/csrng=,iv:leW03hB8eYqrphmqnuwcq4uZMjXKDfTl3d+VKq3CWks=,tag:X7rPeQ88+dHjezqZ2Ts8FQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UUpDaWxGOWRZWkhXMTAr
        cS9GeEFFcUY4OE9RdlZXNHF0WXB6bk5PY2dzCmpTb2YrNUYrWjV4a3JxYTdSdlMz
        SG1qU0VFVVg1cWJITnR6WVl6dVluOGMKLS0tIGZrako4dFpIVVVGMVZrZHVXb3gx
        b2Y0dG9TcmVHd1NPNno0WG8wa2ZybU0Ko4r0W/8KGllbk/y41xlHyaG86kz22v+E
        cSR2Ih7PgIf2u58FVagn1ZIaka4wuYBjDeNtczuFItDTec/UWZUVhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-30T20:12:06Z"
  mac: ENC[AES256_GCM,data:M/Rb6j2oVgZcVkkBPWFOObMgTKwx17YqSeW0wmEQNervX+enrKXhY5dwCUEmUmGTZZdzIf297JbPznqDtOuP7KamIm7MGL1Tu3Y9URecRxAzyohT2md/Br4rW27TnENdVPCYCjOVwSYdgtyiFL7F/mrYNVb5AjhKMpp6YHuT3Ro=,iv:0d6tDRXDGk0WC4+X1U3Hg3f0+p/GNvWQXuvqTxAZznA=,tag:vC7rR6lWEuPlgYPRWLyzYw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.1
