apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:Bzj6TWvpBYpSgpTAf7gls8ov8OCZV+YuBuQMYQxjGW9sN2bWLeMthLYFNCEnrKAR3uU0759X9MWZo5gf5pYKldfWj4RXUZkYFC2ZRTzJiNQIM3L2doNkqf0YlM/i6RnJqFdOvkfN3ikID4FQTvkUepVyLsYrdiOg+u/9BPcRNGhqFHIQX5bE3Fx3k6ZjZzPxPTG/Of/K2nEZpHfYHeCDf5BG9tqQmlQjcPIddZtOG1nZ7g76mOIv,iv:b5NQx9NVQ7fqEvOjsebTQC73cBi/6tog/7MyFCB4ris=,tag:d6/x+xpXs8nsEEvh2fWkeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT2hQZUtOaTBmVXRSK0hr
            UVJudmRTQmRFWUxOVXBya3JBZStTWHkveldZClZPRzBDaE9JMFd3YjdvYUJCVkor
            ZVhXb2FDNjZDTGdyNUNHWnNEbzZ4WWsKLS0tIEMvL2twNGVLTzRNdjhIVmxSckpN
            SWZaNTc0Ym95T3R2U2dITlp2NkRzNWsKQzHs1vFuEpCNH0Ji+D8IbWtwd7eG0+Rw
            a0qgwqybDSKZwUFKbr+b1zP8LMo6OtCBJAWlrdRm9jglIGdcBzsOqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T12:13:18Z"
    mac: ENC[AES256_GCM,data:mJvT4QtFGI0qRZ0rwFDZj4Ljar4lLy/W9WEh/aCbPvDrRqt5lj9KOX9d/TWdtB/84FwIgDzpWyn7F64RXWcwTdKNL5ZD5WwCkLgOfabJbQJrVT346my/E4kwo5UFFztgaErt5h2PGWw9+tz4xj0fHnJ2st8/zukEi7PQe/NN78o=,iv:7JhSC1xEveSvb0ZVT2jAGP4J4uD54mq/lkR2yC0I00A=,tag:Gj/1Dq0SmtNk1D1WMMnKaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
