---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-mcp-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: paperless-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_API_KEY
      remoteRef:
        key: mcps/paperless-mcp
        property: PAPERLESS_API_KEY
