---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mediamanager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mediamanager
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      mediamanager:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.2.0@sha256:ae89578925b480f5972f237dda2f7a37efe36aff500d3e7bd1d3a6a3181e4191
            envFrom:
              - secretRef:
                  name: mediamanager-db
              - secretRef:
                  name: mediamanager-initdb
        containers:
          mediamanager:
            image:
              repository: ghcr.io/maxdorninger/mediamanager/mediamanager
              tag: 1.12.3@sha256:83b80dce26f8cdbbf8afec06784a85e7eedcba05ad4be57d2f70b006304d7a8c
            command: ["/entrypoint.sh"]
            env:
              CONFIG_DIR: /app/config
            envFrom:
              - secretRef:
                  name: mediamanager
              - secretRef:
                  name: mediamanager-db
              - secretRef:
                  name: mediamanager-auth-token
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/health
                    port: &port 8000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    
    service:
      mediamanager:
        ports:
          http:
            port: *port

    route:
      mediamanager:
        hostnames:
          - mm.ds47.dev
        parentRefs:
          - name: kgateway-internal
            namespace: network
        rules:
          - backendRefs:
              - port: *port
                name: mediamanager

    persistence:
      cache:
        type: emptyDir
        sizeLimit: 1Gi
        globalMounts:
          - path: /.cache

      config:
        type: emptyDir
        sizeLimit: 1Gi
        globalMounts:
          - path: /app/config

      entrypoint:
        type: configMap
        name: mediamanager-entrypoint
        defaultMode: 0755
        advancedMounts:
          mediamanager:
            mediamanager:
              - path: /entrypoint.sh
                subPath: entrypoint.sh
                readOnly: true

      media:
        type: nfs
        server: 10.100.0.81
        path: /media/media
        globalMounts:
          - path: /data/media

      metadata:
        type: persistentVolumeClaim
        size: 20Gi
        accessMode: ReadWriteOnce
        storageClass: csi-rbd-sc