apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
stringData:
    api-key: ENC[AES256_GCM,data:3QCGVSsnUmORGUewUjk/ejAOdeMrXMaxfMlMX7FMx9o=,iv:YS7xbgabL2LakfL+Xt3bL/hw4bw0d4hKriBTThk44OU=,tag:U6/tM2PRLXr28ouiSqrGAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqclYwYTNZTnBxVDNhRkYy
            T29rYmtVeXpiS2E4R20zWndYdlhRQVVZTGwwCkxiSzZuYXY2M3IraXRMMlk5ektJ
            QXh3SUVmcWV0VmdMcWtVaXRMdFRlcVUKLS0tIHBiSGhMTmRwRHo4U1RaYjROREZz
            eldVbFFyaEFnY3ZUa2VjMkcvOXoxQTQKBy+aCtqs4EkANos9TbqRgTTr5w1m8cXz
            +Pot8g6P18WbbNwZOkvSxmSkMDQGYL9ZeV3SmUHmtliXZnuJ/zYc8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-08T18:01:23Z"
    mac: ENC[AES256_GCM,data:oDgi9rYlMHHwwuhNRL+Pd2nucLhN0vVO1EXBRzo5qP/g6Me35S/GAW/DoAezM9rPo+/aegCm92KhiXdX14KA0SyA7NmJ0Pu/7GJmffmjG/3bZ6zmkmh3D1LwIUGQJSZPiZJg/NBVFebx+pzo+heCW1eMDnNlQhL9x6grCmHej3U=,iv:lKMUYC/vGVRPrsbHiZYjZHg/yDPf2cFLi8KKujjIhns=,tag:H/eQapL1ztIZlVq2N0u2qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
