---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ollama
  values:
    controllers:
      ollama:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.16.1@sha256:dca1224ecd799f764b21b8d74a17afdc00505ecce93e7b55530d124115b42260
            env:
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_NUM_PARALLEL: 1
              OLLAMA_CONTEXT_LENGTH: 8092
              OLLAMA_MODELS: &modelPath /models
              OLLAMA_KEEP_ALIVE: 30m
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: http
              readiness: *probes
            resources:
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                nvidia.com/gpu: 1
                memory: 16Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        pod:
          nodeSelector:
            nvidia.com/gpu.present: "true"
          runtimeClassName: nvidia
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 11434

    route:
      app:
        hostnames:
          - ollama.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      models:
        existingClaim: ollama-openebs-pvc
        globalMounts:
          - path: /models