---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ollama
  driftDetection:
      mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ollama:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          ollama:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.15.6@sha256:5f7a20da9b4d42d1909b4693f90942135bcabc335ee42d529c0d143c44a92311
            env:
              OLLAMA_NUM_PARALLEL: 1
              OLLAMA_CONTEXT_LENGTH: 8092
              OLLAMA_MODELS: /models
              OLLAMA_KEEP_ALIVE: 30m
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: http
              readiness: *probes
            resources:
              requests:
                cpu: 2
                memory: 8Gi
              limits:
                nvidia.com/gpu: 1
                cpu: 8
                memory: 16Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        pod:
          nodeSelector:
            feature.node.kubernetes.io/pci-10de.present: "true"
          runtimeClassName: nvidia
          securityContext:
            runAsNonRoot: true
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

    service:
      ollama:
        ports:
          http:
            port: 11434

    route:
      app:
        hostnames:
          - ollama.schwarz47.at
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      data:
        existingClaim: ollama
        globalMounts:
          - path: /home/ubuntu/.ollama
      models:
        accessMode: ReadWriteOnce
        size: 250Gi
        storageClass: csi-rbd-sc
        suffix: models
        type: persistentVolumeClaim
      run:
        type: emptyDir
        sizeLimit: 128Mi
      tmp:
        type: emptyDir
        sizeLimit: 128Mi