---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: ollama
  values:
    controllers:
      ollama:
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.20.6@sha256:d5034f60974be528e0a5523ba5e89156e4a9ffd12d0b2b18475fb148237f3d4c
            env:
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_NUM_PARALLEL: 4
              OLLAMA_MAX_LOADED_MODELS: 1
              OLLAMA_MODELS: &modelPath /models
              OLLAMA_KEEP_ALIVE: 30m
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/tags
                    port: 11434
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/tags
                    port: 11434
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup: *probe
            resources:
              requests:
                cpu: 2
                memory: 2Gi
              limits:
                cpu: 8
                memory: 16Gi
                nvidia.com/gpu: 1

    defaultPodOptions:
      runtimeClassName: nvidia
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-10de.present
                    operator: In
                    values: ["true"]

    service:
      app:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ollama.ds47.dev
          lbipam.cilium.io/ips: 10.100.10.205
        ports:
          http:
            port: 11434

    persistence:
      data:
        existingClaim: ollama
        globalMounts:
          - path: /.ollama
      models:
        existingClaim: ollama-models
        globalMounts:
          - path: *modelPath
      run:
        type: emptyDir
        medium: Memory
        sizeLimit: 128Mi
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 128Mi