---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stash
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: stash
  dependsOn:
    - name: ceph-csi-rbd
      namespace: storage
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: stashapp/stash
              tag: v0.31.0
            env:
              STASH_STASH: /data/
              STASH_GENERATED: /generated/
              STASH_METADATA: /metadata/
              STASH_CACHE: /cache/
              STASH_PORT: &port 9999
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 2G

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - stash.ds47.dev
        parentRefs:
          - name: kgateway-internal
            namespace: network

    persistence:
      config:
        existingClaim: stash-config
        advancedMounts:
          stash:
            app:
              - path: /root/.stash

      cache:
        existingClaim: stash-cache
        advancedMounts:
          stash:
            app:
              - path: /cache
                subPath: cache
              - path: /blobs
                subPath: blobs
              - path: /metadata
                subPath: metadata
              - path: /generated
                subPath: generated

      media:
        type: nfs
        server: 10.100.0.81
        path: /media/media/media/adult
        advancedMounts:
          stash:
            app:
              - path: /data
                readOnly: true
