---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - ./continuwuity/ks.yaml
  - ./element-web/ks.yaml
  - ./mautrix-signal/ks.yaml
  - ./namespace.yaml
components:
  - ../../components/common
