---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dragonfly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: dragonfly-secret
    template:
      data:
        DRAGONFLY_PASSWORD: "{{ .PASSWORD }}"
  dataFrom:
    - extract:
        key: dragonfly