apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lFkULCtbfNR815Y1pnckAJkRGBQEJDdNYQMLX6N2hQs=,iv:JssdpJw1JWmIrv1RA5h6sbPcwweJGURKNeBwaiOrXDU=,tag:Xho+eRQds4U3LdC/PyVdow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkM5NXJEMUxpRFErYXRV
            S1J0dzBJenVIeGMvQlFsbXNERHpCaXc5akU4CnNJdXArSUhOclZMdGp6MjFST0ht
            am8rampUbTNKanE4SDh3WkZudk5TRGcKLS0tIC9ncWRmTXE5ZVBrNEh4YVRpeW1u
            Z2RiazVJc1lVcXZBL1hORGk3U29qTzgK1I+2FgZlsvQg8NtppAbg/skO9z8sqga2
            OQg6qEgjBqhFQj1frwVAZxZmwqRHkTOxPN4tnzP2+wucE0p1NC/zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:25:01Z"
    mac: ENC[AES256_GCM,data:tDe/DWyJlVJ3WMokESbUtYTLzDWHFosoRI+gRHgfIjkoJ5DDKdun+yT9o5sWcZPWLdLFrD1WWFxP1cepFvu0tDwfiSEfeTHv3gswZPFYVXUFlUjmFp6mH6qxQ/0zZl4CSsYhWVd44+VDrsPkh+33443tB2yB5bT8EAWz1amuOhc=,iv:FD7Q3sVuHSxEzX3NLJPCA4FGYr4YYQqXW1R+bK+3RFU=,tag:6OnHkJaKJhuWXUFNDX818w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
