apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:PioLvs2rkOxEfOI12Hqvw3ahaJalBppwSc7d6cX4+Vg=,iv:9a6zZBacwo+UbzgUexepoHPgPiVlbYASF0cswhvBjuo=,tag:SaCranIqvK1bqERe44JUyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d1p5T3V1dXZCa0N4SkN1
            Y09HdDBtaUJDc1dzTllkVXcvVk8zMjFoYmtZCmhMZDVKWWZ4Y0REa015Szg1TWFB
            cGhkOEFuVWFwZ3A4NElQSlQxSEVkMXcKLS0tIGdHdklKSXNuNEhMTUlKV3R4eFAx
            dEkrRFUrWnJMKzVhb1F1aXNsM1hobUUKf1jfotDGvM/e0znj3YwMLnPcHuDlIK/c
            N+0BylMlrejEVL3QOQfzfQ+rPIpyzUv6ge3Mhl8FzuWcKlP1Na705Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T09:28:25Z"
    mac: ENC[AES256_GCM,data:bWadg0Gw6VV+Slc7GqDQBj7bHOEfoo5oKZi5Sn2Atsjlj07tM9ZjcTuAMbCI6fpz4mJAgrwZBen5Dby+WvteR2uKcgRLQ2jggxte9+9D3ZWXtr/CqTBxDbdflghuc/kdaAGFtuTmDc2+BgRj8eBYVFFxzzgKNj7IvYGoQEZIQ7E=,iv:x7fpbtyJvNZ+8XHLzcRlC47Bk4uFxPL1bnhuM9b3W0o=,tag:zn5GoEQxFp7OXC5WcS+EMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
