apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:4Or6PKEvKRt1WUq4hYb3R2M4TyQZUpLUH8W64G/SbFQ=,iv:4RU5hKJ96CsmWZ29RYCWLmIkpzmEPcsK+8xAaTkgcJk=,tag:gIVrCnLBMuYDEDVFj4Cw+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQzB3bkl2TURqd1dUVHpC
            dHFaWE14ZkhzRHl6SUozUFQ0SjEvdm9XaHljCkdENGZKWTYxZHNnMUw1S0dwZUYy
            T0N6NTdjT0t0dGJoRlVtQUhzV2lCcmMKLS0tIDFsN2tNUVo1M3NCdnJBMlhONExp
            bEZwWlAyRFhOWGcrbG5yY25KTjRncWMKVNgn0TWnvPVUg8tsqPG85j/W+CAB/Wh/
            UCSOje9LHM8naxQA9JceJkpKqKmdtoUDNcMISxWffKWNpFTh6oO1Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T23:31:00Z"
    mac: ENC[AES256_GCM,data:EViolr2DcPm0NUwfr5pBIGwp15hNtEdIEm5jjkr7zaxrXbnfUe6CJZOQGOFQQSjQCUOX59/Nyq3w+OJkYGivtsVMSfEpyrp5T08AnSFo0zSOcG+eCC1q8G9Srl+hTYxb6tajNUx38zT6fdzaBr6osWiZmUfu9BV7b3Y3cKyg25U=,iv:rGxSXwi9w1h/Qo3c5bCnKr6w1C8DtOFDYXRGDlCxsfk=,tag:9q37c4j+5NjLdScpoiRRGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
