---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redlib
spec:
  chartRef:
    kind: OCIRepository
    name: redlib
  interval: 30m
  values:
    controllers:
      redlib:
        replicas: 2
        strategy: RollingUpdate
        pod:
          securityContext:
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 65534
            runAsUser: 65534
            runAsNonRoot: true
        containers:
          app:
            image:
              repository: ghcr.io/evrial/redlib
              tag: latest@sha256:e6647a94d553bf3f7c95c53fc6d9da5785e6c278d9002e99ea32abdb5e3c513a
            env:
              REDLIB_DEFAULT_SHOW_NSFW: "on"
              REDLIB_DEFAULT_WIDE: "on"
              REDLIB_DEFAULT_USE_HLS: "on"
              REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION: "on"
              REDLIB_DEFAULT_REMOVE_DEFAULT_FEEDS: "on"
              REDLIB_ARTI_PATH: /tmp/arti
              REDLIB_ROBOTS_DISABLE_INDEXING: "on"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /settings
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 5m
                memory: 256M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: redlib
        ports:
          http:
            port: *port

    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp/arti

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.ds47.dev"
        parentRefs:
          - name: kgateway-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
