---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./qwen3.6-9b.yaml
  - ./deepseek-r1-8b.yaml
  - ./llama-3.2-8b.yaml
