---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deepseek-r1-8b.yaml
  - ./lfm2.5-8b-uncensored.yaml
