---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nsp-manager
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      nspmanager:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-nginx:
            image:
              repository: busybox
              tag: 1.28
            command: ['mkdir', '-p', '/etc/nginx/sites-templates/']
          init-initd:
            image:
              repository: busybox
              tag: 1.28
            command: ['mkdir', '-p', '/etc/init.d/']

        containers:
          main:
            image:
              repository: nspanelmanager/nspanelmanager-amd64
              tag: 1.0.4@sha256:0f765cb00fede227a042124458db218669a542b0d437ea06e66646fd4d170bf2

            resources:
              requests:
                cpu: 47m
                memory: 128M
              limits:
                memory: 512M

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL


    service:
      app:
        controller: nspmanager
        type: ClusterIP
        ports:
          http:
            port: 8000

    route:
      app:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: network
        hostnames:
          - nsp-manager.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: app
                port: http

    persistence:
      config:
        existingClaim: nsp-manager-config
        globalMounts:
          - path: /data

      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
          - path: /etc