---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app speedtest
  namespace: &namespace network
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-pg16
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
    - name: ceph-rbd
      namespace: ceph-csi
    - name: volsync
      namespace: system
  path: ./kubernetes/apps/network/speedtest/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: speedtest-config
      VOLSYNC_CAPACITY: 1Gi