---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: csi-rbd-secret
    template:
      type: Opaque
      data:
        userID: "{{ .USER_ID }}"
        userKey: "{{ .USER_KEY }}"
  dataFrom:
    - extract:
        key: ceph
