---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: slskd-secret
    template:
      engineVersion: v2
      data:
        SLSKD_API_KEY: "{{ .SLSK_API_KEY }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSK_PASSWORD }}"
        SLSKD_SLSK_USERNAME: "{{ .SLSK_USERNAME }}"
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
        GLUETUN_API_KEY: "{{ .GLUETUN_API_KEY }}"
        GLUETUN_AUTH_ROLE: '{"auth":"apikey","apikey":"{{ .GLUETUN_API_KEY }}"}'
  dataFrom:
    - extract:
        key: downloads/slskd
