---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${VOLSYNC_NAME:-${APP}}-bootstrap
spec:
  trigger:
    manual: restore
  kopia:
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:-5Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    repository: ${VOLSYNC_NAME:-${APP}}-volsync-secret
    storageClassName: "${VOLSYNC_STORAGECLASS:-csi-rbd-sc}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-rbd-snapclass}"
