apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgresql
stringData:
    postgres-password: ENC[AES256_GCM,data:ChTrmvc7iBK18yJL8VZETPw5NFDhWypPqNvKkhQXsQX0OiIw,iv:wH7+soVx+sFsDEjcNOUd6DcnO4Uhvgj13CXagF8Qw8E=,tag:ZpQYIez5kgnfJqRVrwFCYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod2VDTHJHZWltNnZPa1hV
            L2pQeFdjamdPQVUzZ3BaMk42ZDVoRXowV0h3CnhFVjgycnFkc2VoRU1RV3IwU2s2
            QlM4Y0NLRzMzakRmS2xFOTB2bGJiNmMKLS0tIElpaWw3d1E2bUpSWVpId2JhdE5t
            RzBtTmRjTURhcjcxNG85em9FQ29VOUUKlYdkDEbmBQ7TAlOdn2KkzMCoh/xCTu+X
            w6D2luH65Mz4vNwUE2v08BZ0nnRH1zDsISSyRu6FehRjJHTANKdMUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T20:25:51Z"
    mac: ENC[AES256_GCM,data:yQj4A0vtc8qfGmVgw8DMqGOFsMQk02XDwxPyLGV1p7AIUhUDF1NbEtarRMtC2Ok0loo/ghowdhpcKGestxGT0QZbVmTgkn1XJBKPBYFSWUi0CMCvTP3WQDVg+TUwSJ1s6Tz5CCY53wmm9hS0hcf0y8ECGbTgU4+cDWOy+EuXbdA=,iv:bP05GOaIZexpjAER/moPvwnGnHD1NyKkWFfmB/q5Kvc=,tag:kUtCG02s127a5ikjZVjPBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
