apiVersion: v1
kind: Secret
metadata:
    name: paperless-redis
stringData:
    redis-password: ENC[AES256_GCM,data:cD6KZbtjD4N4zGzXAs5ALfDCbwwsvloL47TrbfzrhM1Yb0On,iv:wo+7HwkbcG9HeHqYxOMYR+qKt+eKVjxd/z3GFPFdoCQ=,tag:m8INR3UT6denK7rOGCJQBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod2VDTHJHZWltNnZPa1hV
            L2pQeFdjamdPQVUzZ3BaMk42ZDVoRXowV0h3CnhFVjgycnFkc2VoRU1RV3IwU2s2
            QlM4Y0NLRzMzakRmS2xFOTB2bGJiNmMKLS0tIElpaWw3d1E2bUpSWVpId2JhdE5t
            RzBtTmRjTURhcjcxNG85em9FQ29VOUUKlYdkDEbmBQ7TAlOdn2KkzMCoh/xCTu+X
            w6D2luH65Mz4vNwUE2v08BZ0nnRH1zDsISSyRu6FehRjJHTANKdMUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T17:00:45Z"
    mac: ENC[AES256_GCM,data:d+N7dPqCEOSZeo1IYSDA3pJLSqsNO2X1CWzzrMrn5ZTCLWGQUV1tGJNkxUURHXJrjtqmlV3jWwWAT3EeJU4XHlAAOeQxDHf3QI/c6pdNZ58cn9lo2ON3tEHHxnwqqPVvh2wktfh7915PuhbbIb36QEVyEo56WIYZj1tJYQmuM0k=,iv:zMxXW740s0spwhG59C6bTSRdmqp7oRHfaW9WwHLw7IA=,tag:/xrHLCOd2CCcSViIsHeluA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
