apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:YJauYx1C7A==,iv:/y7RH4y+GV9RkBFnpgN+CnmRdl//5QFMJ2BT3/w6FvQ=,tag:2eNM7g2ieQF80fqqEC92jA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:kBNSsS3zkRtIDtU=,iv:yOv6eFR96LSmA92OoeQqb0ThTwM/XTMvLqnefAYeTzo=,tag:lt4OCc5J6swbMAe1uWVsaQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:DuhVXxU59XYT0/KXeWG+NhVl2Vk7Y5IVcJtIsqyv0bxG0Ty6,iv:rO2qHPcjiO7wTaBtLJx4F1os79kPR8W6aQAtlJO5khU=,tag:cR3auSsGBDVqbsLHJnZnAA==,type:str]
    PAPERLESS_REDIS_URL: ENC[AES256_GCM,data:tc96Q0r64XzFOT75N+/Qay1OhlvT5zGQKxMQ6FIPt7yu32GRQrA3eQQFpfC2H2Wp2AS3NzNqOXExb7IEfbcUkzjROzgjfwvXTTOsLUAo+altctUkxEURElziGULqnts=,iv:ruVOpl18a4IS8e2mw1WV4mFG0X8iqb3fCHv53JU5XH4=,tag:DU8v9iWbWV/RkMZy5m6vrQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:ViY39VkcwZtPl9GqrgmfjuUaL6wsdk7E0ho+nN3be1tKEhiD,iv:gWs5GVvV6+1ehNn/q38pUCZpYWED1gVRKJ5VWevIgs4=,tag:El+uaX3FFKq4Z28M1N/1IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeDNlck1sUnVaUU8xd01Y
            SGhlbnV0OG0rS1VLYTJFOFk3WURTanBiN3lvClAvV2RGTktCN2lVUVRNbHAxbmdU
            cFMyVWw3TmdTaVQ1MHlhaEtRZldtM2cKLS0tIEZKa1VjNjloSTRXdWI0M1V6Z01T
            UlBkY0JyVGNMKzdoNlhkSER5QWIrOXMKex+joTU5RnbBcpkv3qfVVzgHC9RldstT
            ptTEpyvWI+TQroKbBeU8ZKOonnHott1UhLqFtEvdHBrQf1doRj0F2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T07:37:02Z"
    mac: ENC[AES256_GCM,data:6oBb/J3U1gTBJp0iY2laZ7GjP3zYGOPnFQxpsc6HVNmXhAlgQs33jQvr03znZ8XJbOdVubkRB/yGfB20vvZOL6NqgMoXTUHU9ujnOjTmc8Kva868cjHiVSNJnmPW9ngkvuMRIQUifJEkUUyhAiXPuoW8o2NfHKEK6SrPMtCr9A0=,iv:3EivC9XC68KGSFI/PyqS89rXXKVlvxI9bMQQ873iqOE=,tag:/zXln/H0GVFvnVYl6njmsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
