apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_ADMIN_USER: "dominik"
    PAPERLESS_ADMIN_PASSWORD: "Revogaxu!47"
    PAPERLESS_SECRET_KEY: "t[2:F(qpD&fyV0?z:TKJE84*C*k:jHEg3Drv"
    redis-password: "x22)S>suNjBkPJT2xHx2sxfrp6]JF3QAmexz"
    postgres-password: "SP.eT)5@qbuhEqEUMK#;sy8yg7X=cANf=W5#"
