apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:jlTdpU5XXQ==,iv:UUtjOScK+zSY0APF/mM8R+Vj+owRLqFmBPe3V7u/YCk=,tag:DCQBhBDgNqG2MZDmnqgcLQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZzRv57GPwG4A03I=,iv:8NgYpFE4YxJsVk+FJCgpz6ZwTVh4i5C8SBEwHAcRkhA=,tag:sQEMTWzkIMpEyQMm631Cwg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:nhuyR4Lr2t9bRCiePRXbnMZojFVArcnCSpR0A//gwO1w7f/H,iv:qwX2olIeYofzNhnuOhAGvEX4Phi4CcczwzvdePXXmXE=,tag:3wRsBDzstvb1sUWiz9ZTyw==,type:str]
    redis-password: ENC[AES256_GCM,data:cbZSbCeZ9DKjEyy7IPlgUYbBYSchbACjFUJorgjZNJoW0vuI,iv:lhRkLpgGw8L01iNP9TNkYqNIxFqUHH2Fcocxc8uavzM=,tag:Nkqp6Tez08oO/omV4cwCfg==,type:str]
    postgres-password: ENC[AES256_GCM,data:2kPm1l4O6wG37SDRhEPLXbnINDjuciQ5vyBBNxb11q2HNPgY,iv:ohtrCSol4UJBN0CFlXN4k7nvqqNWmeGTl9L21NBg0kw=,tag:kxmMaRC+4C03bZ0LKu0NRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjZ5ak04R0tsaklsekNY
            VXpvODdWMU1JWUo0djBhWG9LcEhpSVpYWW13CmMxa1pza0p2bUIxNGF6ZFFLMDN1
            dHBXckQxZVhvVnpjSHpwSU5EbUVVTkUKLS0tIGhYSm91TkI0UWxFT1RyS0l0TWJ2
            MU1ReDFzRG1VOXhNSFNObG1KL2pJU1kKFlaLg0WQNYg8m9Y+xZ2xZQhSYTsvO80d
            yJPVNqaVpp61zlPN+5NCPkPpBs3MFe9M5fi1TlQVSxQ0GWsNmxuUWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T09:42:59Z"
    mac: ENC[AES256_GCM,data:g7FqaEHCWaFKP1crWZyiCC7rdLn65nZVwrwbczgbi97GKIdHLCwwzXqNlbwqEuPWkcNPqccinOJSwMHbHqVEJjtF+jvSbquqyuuPBB4oJ+YdLl1CEDhnzBMudCmo3u4NJ3dcxsw4Czs4rZbUawwFpST6pGxoVPRuGKFpg6mxuYQ=,iv:alire+iluHxVJ/tgrpJKahrHpIVNvnaUuiH0ZrzOL6k=,tag:9bYCA+rA54Fgii5p8oPAIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
