---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database.yaml
  - ./redis.yaml
  - ./init.yaml
  - ./config.yaml
  - ./deployment.yaml
  - ./http-svc.yaml
  - ./ssh-svc.yaml
