apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
spec:
  selector:
    app: forgejo-ssh
  type: ClusterIP
  ports:
  - name: forgejo-ssh
    protocol: TCP
    port: 2222
    targetPort: 2222
