---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      data:
        # App
        nextcloud-username: "{{ .NEXTCLOUD_ADMIN_USERNAME }}"
        nextcloud-password: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        # Database
        POSTGRES_HOST: &dbHost "pg18vec-rw.database.svc.cluster.local"
        POSTGRES_USER: &dbUser "nextcloud"
        POSTGRES_PASSWORD: &dbPass "{{ .NEXTCLOUD_POSTGRES_PASSWORD }}"
        POSTGRES_DB: &dbName "nextcloud"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        # OIDC
        OIDC_CLIENT_ID: "{{ .NEXTCLOUD_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .NEXTCLOUD_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: nextcloud
      rewrite:
        - regexp:
            source: "(.*)"
            target: "NEXTCLOUD_$1"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: nextcloud-initdb-secret
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vec
        property: password