---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      data:
        # App
        nextcloud-username: "{{ .NEXTCLOUD_ADMIN_USERNAME }}"
        nextcloud-password: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: nextcloud
        INIT_POSTGRES_HOST: pg18vec-rw.database.svc.cluster.local.
        INIT_POSTGRES_USER: "nextcloud"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        # OIDC
        OIDC_CLIENT_ID: "{{ .NEXTCLOUD_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .NEXTCLOUD_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: nextcloud
      rewrite:
        - regexp:
            source: "(.*)"
            target: "NEXTCLOUD_$1"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: nextcloud-initdb-secret
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vec
        property: password