---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-db
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: netbox-db
    creationPolicy: Owner
    template:
      data:
        NETBOX_PG_PASS: &dbPass "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_DBNAME: netbox
        INIT_POSTGRES_HOST: pg18vec-rw.database.svc.cluster.local
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: netbox
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: netbox-secret
    creationPolicy: Owner
    template:
      data:
        # S3
        # AWS_ACCESS_KEY_ID: "{{ .NETBOX_AWS_ACCESS_KEY_ID }}"
        # AWS_SECRET_ACCESS_KEY: "{{ .NETBOX_AWS_SECRET_ACCESS_KEY }}"
        # App
        email_password: ""
        napalm_password: ""
        secret_key: "{{ .NETBOX_SECRET_KEY }}"
        api_token_peppers: '{"1": "{{ .NETBOX_API_TOKEN_PEPPERS }}"}'
        # Superuser
        username: calautigo
        email: server.netbox@ds47.dev
        password: "{{ .NETBOX_SUPERUSER_PASSWORD }}"
        api_token: "{{ .NETBOX_SUPERUSER_API_TOKEN }}"
  dataFrom:
    - extract:
        key: netbox
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-initdb
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: netbox-initdb
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vec
        property: password
