---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: netbox
  values:
    podAnnotations: &reloader
      reloader.stakater.com/auto: "true"
    initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
        envFrom:
          - secretRef:
              name: netbox-db
          - secretRef:
              name: netbox-initdb
    storages:
      default:
        BACKEND: "storages.backends.s3.S3Storage"
        OPTIONS:
          bucket_name: "netbox"
          endpoint_url: "https://versity.ds47.dev"
          region_name: "us-east-1"
    worker:
      enabled: false
    housekeeping:
      enabled: false
    updateStrategy:
      type: Recreate
    replicaCount: 1
    allowedHosts:
      - netbox.ds47.dev
    csrf:
      trustedOrigins:
        - https://netbox.ds47.dev
    timeZone: Europe/Vienna
    existingSecret: &secret netbox-secret
    superuser:
      name: calautigo
      email: server.netbox@ds47.dev
      existingSecret: *secret
    admins:
      - ["calautigo", "server.netbox@${SECRET_DOMAIN_SHORT}"]
    dateFormat: "j. F, Y"
    shortDateFormat: "j.m.Y"
    timeFormat: "G:i"
    shortTimeFormat: "H:i:s"
    dateTimeFormat: "j. F, Y g:i a"
    shortDateTimeFormat: "j.m.Y H:i"
    metricsEnabled: true
    persistence:
      enabled: false
    httpRoute:
      enabled: true
      parentRefs:
        - name: kgateway-internal
          namespace: network
      hostnames:
        - netbox.ds47.dev
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
    postgresql:
      enabled: false
    tasksDatabase:
      host: netbox-dragonfly.home-automation.svc.cluster.local
      database: 1
    cachingDatabase:
      host: netbox-dragonfly.home-automation.svc.cluster.local
      database: 2
    externalDatabase:
      host: pg18vec-rw.database.svc.cluster.local
      port: 5432
      database: netbox
      username: netbox
      existingSecretName: netbox-db
      existingSecretKey: "NETBOX_PG_PASS"
    valkey:
      enabled: false
