---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/main/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: netbox
spec:
  name: NetBox
  launchUrl: https://netbox.ds47.dev
  callbackUrls:
    - https://netbox.ds47.dev/oauth/complete/oidc/
  secret:
    name: netbox-oidc
    keys:
      clientID: NETBOX_OIDC_CLIENT_ID
      clientSecret: NETBOX_OIDC_CLIENT_SECRET
      issuerUrl: NETBOX_OIDC_ISSUER_URL
