---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-versity
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "* */6 * * *"
  restic:
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-openebs-hostpath}"
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${APP_UID:-1000}
      runAsGroup: ${APP_GID:-100}
      fsGroup: ${APP_GID:-100}
    pruneIntervalDays: 2
    repository: ${APP}-volsync-versity
    retain:
      daily: 4
      within: 2d
    storageClassName: "${VOLSYNC_STORAGECLASS:-csi-rbd-sc}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-rbd-snapclass}"