---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calautigo-assistant-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: calautigo-assistant-pem
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: github
        property: calautigo_assistant_app_key