---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: music-assistant-music-static
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "music",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens20.30",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "addresses": [
              {"address": "10.10.30.151/24"}
            ]
          }
        }
      ]
    }
