---
apiVersion: v1
kind: Service
metadata:
  name: newt
  labels:
    app.kubernetes.io/name: newt
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: newt
---
apiVersion: v1
kind: Service
metadata:
  name: newt-cluster
  labels:
    app.kubernetes.io/name: newt
spec:
  selector:
    app.kubernetes.io/name: newt