apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:d/s89UTg4klCjcjBqn2fxLK66IAb2u9adF8Km2APiO7yDiW+SxvRSw==,iv:oLB7rxHl5EhV6DsKRVikUj7xciudNS4xAHf/vcSjCnY=,tag:5qfBGF4/3gITHfJ1OYS8Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldGtlaFdJV0NqYk9ROVYw
            eUFEamdObTBPZzlXc0NOblQxaXRyZmE1MzNFCjlFRksrQkxGcVA4bzhBRGlSWXRp
            SHZnUVd3Z3lIbTVRdFhPM1FNT281MEEKLS0tIGM2L2RrM2xHZFZ1ZmQ4cFhzVkxP
            UFJIQzMvc1JyVFVyVllKNU54K1FVMkEKa3cgW8oJ606LkWPmAVZx2qv/sz7fpt+w
            5R4RQmz9hay9klk+5vSTdAqfAmVjAyqfNybUmhzcHPeuxhI9sg5OVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T08:25:01Z"
    mac: ENC[AES256_GCM,data:cpldCKkmuNbgEIJ+acN9TyFMc84dQHSCDCnxRH3OmkEGnOQ7M5vop7B67IMaay4KpZWq4tIQHYX1dyE0Qe/WeIaksMXOnJ/FOA4Tq864NSl1b1HRRaNOXMJCJL6vVFGQaao8w1hAKMokuNy2tiL5qxUwqb9VJzvpwg1ecyJINCM=,iv:UI44fMFHzgPMq4pkj3zTcwuEHiY2D4JL9dMibVKgbl8=,tag:CSMHdJa0osTx4XJ1k2G9Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
