apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:oenCs+d0eUY8Pskx9aps5uWe4qBG+6Tzm3xuNPQnqCwbN0vvf4NDtA==,iv:9e3PAJheklzEtCI5k357w8VYXobIRl2QLdlBW++gGz0=,tag:uB8X/TypFJqZOUvPooVLpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOeWVYaTJDeUlPQzFFNXZ0
            aXJBdTlrbG5JWmFjWm1tSlZLR0VIaml0TVRZClVtck8yQnVKWmgyR2hnY0s1bzFZ
            VHRXNWdKTkRXVzBBcHJVVSt2bEJmaWMKLS0tIHAyOW10Z3hPUWJLNXRFUlQrUW1k
            OG5PWStQRXVGNVdDSUFEMmlRalV1V0kKKKPWfk7UfAmL51KPb1/9W/Yah+cOHnUP
            oDemLhoYRQDpfP2j1QgpcFV1aHz870pzpVVkZhN51uxrg2Ke1oA/CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T10:50:38Z"
    mac: ENC[AES256_GCM,data:4vUlbXF1b7L+TB47nZlA5sEDr9ZB7K8VZbOh64Dgo8ojxm2gVGYQ9XczuMVmXWpd5Qzz3cN3yz40gTX69sv5iZHNsBQkLv37x1jORiQ6aZcBpFs5niWMuih9Rw6Bv58bP6SHnYMoGXY9xlevIswFyv6gbkfVRIZGzcjJoUqUlww=,iv:nlFJ1VEuh7g6qAbQMfEslCdZ05UjKeZe8vol3XqmFLg=,tag:Xozt93st/cj+Q2n6gxV+zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
