apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:XYKsi7RdlBPW4HXF0bZbIwnuCjSWU8fH1bJDfEHCUCFpx/Y0vEJd4Q==,iv:0YzO8gaTMIo9kVz6tUdvt+xycfG4G0GtLUNxlXVeP4c=,tag:qVo8SufVyoP0TI0slwkHIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1073mcvy7lha3qgk4ssjqq9l47yqvv8urdxl0q3e6nu83n42m2cjqhwfwdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWI3M0tIZVRFMzZ4NDBk
            NU1xRXdXLzlLUXlkemhtZXg2bjFTNkx0cjFzCk54OGttNVpRc0wxQm1HKzZiSzJs
            Z1RtTHRWNm1EOXBtVGdPUGhNZzJjb2MKLS0tIHkvbWIwRktUb2FJNkltZXd0NlRy
            OUZ6VU5maWo1cGdjMktLS2I1TVJoencKDhE8Xv10z8viEPT08tXgOXFms9cleKhp
            v2JacvMxM5UchaAOZDXX4fmmyGQhjiMzSs00iHEOO2r1X6DTgvwJtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T09:24:26Z"
    mac: ENC[AES256_GCM,data:FxgAp2uZn8T2+lkz/sQNOrvCbCCogDS/DRcDUG54Bq0ivtZLBwHe+5ftPM+5LxS5YHiDzyZQVZC2AypaLrBVHj0iW0y64nzp6WFxgug6H35XSdgvXMiRJzfi25iXA621MK9kckV0ug71K8JI7dDTd2Oa/7PqKqWmD4/WCfkzFak=,iv:LupDcnVjNxGWzywjlOh/YUOpyiR0A6VnTr8jLdLWFoU=,tag:ZrFqL7weyNWIGbXOkxfXrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
