apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.gryffindor.prod.schwarz47.at"
      path: "kv"
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token