---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: immich-secret
    template:
      type: Opaque
      data:
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USERNAME: &dbUser "{{ .IMMICH_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .IMMICH_POSTGRES_PASS }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg