---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [65537]
    controllers:
      immich-server:
        annotations:
          reloader.stakater.com/auto: "true"
        labels:
          app: immich

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 17.4
            envFrom:
              - secretRef:
                  name: immich-secret
          02-init-extensions:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 17.4
            env:
              - name: PGDATABASE
                value: immich
              - name: PGUSER
                value: postgres
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: INIT_POSTGRES_SUPER_PASS
              - name: PGHOST
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: DB_HOSTNAME
              - name: PGPORT
                valueFrom:
                  secretKeyRef:
                    name: immich-secret
                    key: DB_PORT
            envFrom:
              - secretRef:
                  name: immich-secret
            command:
              - /bin/bash
              - -c
              - |
                psql <<'EOF'
                  ALTER SYSTEM SET search_path TO "$user", public, vectors;
                  CREATE EXTENSION IF NOT EXISTS "vectors";
                  CREATE EXTENSION IF NOT EXISTS "cube";
                  CREATE EXTENSION IF NOT EXISTS "earthdistance";
                EOF

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.125.7@sha256:217cddb1e0fa3f4878e1573fe1fd4b9dc24f737015cc5c917910787a5ec0f85e
            env:
              # General
              LOG_LEVEL: verbose
              IMMICH_MEDIA_LOCATION: &mediaPath /usr/src/app/upload
              # Ports
              SERVER_PORT: &port 2283
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                 name: immich-configmap

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4096Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
                  successThreshold: 1
                  timeoutSeconds: 1



    service:
      app:
        controller: immich-server
        ports:
          http:
            port: *port

    route:
      app:
        enabled: true
        parentRefs:
          - name: cilium-gateway
            namespace: network
        hostnames:
          - photos.schwarz47.at
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - kind: Service
                name: app
                port: http

    persistence:
      data:
        existingClaim: immich-data
        globalMounts:
          - path: *mediaPath
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp