---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-s3-backblaze-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: s3-backblaze-secret
    creationPolicy: Owner
  data:
    - secretKey: s3AccessKeyId
      remoteRef:
        key: zalando-postgres
        property: AWS_ACCESS_KEY_ID
    - secretKey: s3SecretAccessKey
      remoteRef:
        key: zalando-postgres
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: s3Endpoint
      remoteRef:
        key: zalando-postgres
        property: ENDPOINT
    - secretKey: s3Bucket
      remoteRef:
        key: zalando-postgres
        property: BUCKET