---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname gateway-int.ds47.dev
spec:
  gatewayClassName: kgateway
  addresses:
    - type: IPAddress
      value: &ipv4Address "${LB_IP_KGATEWAY_INTERNAL}"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
      lbipam.cilium.io/ips: *ipv4Address
    parametersRef:
      name: kgateway-params
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: ds47-dev
      protocol: HTTPS
      port: 443
      hostname: "*.ds47.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: ds47-dev-tls
    - name: schwarz47-at
      protocol: HTTPS
      port: 443
      hostname: "*.schwarz47.at"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: schwarz47-at-tls
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-internal
spec:
  jobLabel: kgateway-internal
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: http-monitoring
      path: /metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kgateway-internal
